### ISSUE TITLE
Avoid reporting "Invalid Nonce" when removing a transaction if it can be found in the chain

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#1485] opened 2015-03-31 18:20 UTC
I'm deploying and executing a series of transaction to a contract on a fresh chain, and it all works well except there are some weird log entries. Actually the web3 `pending` filter only receives `null`, but that may be a web3 thing I suppose. The events seem to happen.

Did this sequence a number of times and the same error. Also this was around before the latest commit (the ethhash API one).

Latest develop (`3efcc49bdfdc751dc17a1fc63f6337d1e7b00bad`), FATDB enabled, ubuntu, amd64 etc. 

Aleth log output. Highlighted the weird entries but again - things still work. It does not discard the txs, it both deploys the contract and transacts to it (contracts list and solidity event watches confirms that).
```
Maximum total cost is 10500 finney.
--- [ 19:59:58 | main ] startWorking for thread eth
*** [ 19:59:58 | main ] New transaction {[CREATE]/0$0+1050000@10000000000000<-909a6c43… #1950}
/S/ [ 19:59:58 | eth ] Paying 10500 finney from sender for gas ( 1050000 gas at 10000 Gwei )
*** [ 19:59:58 | eth ] Additional transaction ready: Restarting mining operation.
*** [ 19:59:58 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
(o) [ 19:59:58 | eth ] !!! 5 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 19:59:58 | eth ] !!! 12 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 19:59:58 | eth ] !!! 14 0000000000000000000000000000000000000000000000000000000000000000
*** [ 19:59:58 | main ] FIRING WATCH 5 1
(o) [ 19:59:58 | main ] Pending transactions changed!
(o) [ 19:59:58 | main ] refreshPending()
(o) [ 19:59:58 | main ] refreshAccounts()
*** [ 19:59:58 | <unknown> ] FIRING WATCH 14 1
*** [ 19:59:58 | main ] FIRING WATCH 12 1
(o) [ 19:59:58 | main ] Pending transactions changed!
(o) [ 19:59:58 | main ] refreshPending()
(o) [ 19:59:58 | main ] refreshAccounts()
*** [ 20:00:00 | miner-2 ] Completed 5f743aa0… 7e52170a… 131072 1
--- [ 20:00:00 | miner-2 ] Completing mine!
*** [ 20:00:00 | miner-2 ] Mined 455ea9dc… (parent: 76a69f46… )
=B= [ 20:00:00 | eth ] Attempting import of 455ea9dc… ...
/S/ [ 20:00:00 | eth ] Paying 10500 finney from sender for gas ( 1050000 gas at 10000 Gwei )
--- [ 20:00:00 | eth ] treeRoute 76a69f46… ... 455ea9dc…
--- [ 20:00:00 | eth ] treeRoute 7 ... 8
--- [ 20:00:00 | eth ] to: 7 455ea9dc…
=B= [ 20:00:00 | eth ]    Imported and best 1179648 . Has 0 siblings. Route: [ 455ea9dc…, ]
*** [ 20:00:00 | eth ] New block on chain: Restarting mining operation.

************************************* WEIRD PART *************************************

/S/ [ 20:00:00 | eth ] Invalid Nonce: Require 1  Got 0
*** [ 20:00:00 | eth ] Dropping invalid transaction:
*** [ 20:00:00 | eth ] /home/androlo/cpp-ethereum/libethereum/Executive.cpp(96): Throw in function void dev::eth::Executive::initialize(const dev::eth::Transaction&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InvalidNonce>
std::exception::what: std::exception
[dev::tag_required*] = 1
[dev::tag_got*] = 0

*******************************************************************************************

*** [ 20:00:00 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000, 0000000000000000000000000000000000000000000000000000000000000001 } )
(o) [ 20:00:00 | eth ] !!! 5 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:00 | eth ] !!! 6 0000000000000000000000000000000000000000000000000000000000000001
(o) [ 20:00:00 | eth ] !!! 12 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:00 | eth ] !!! 13 0000000000000000000000000000000000000000000000000000000000000001
(o) [ 20:00:00 | eth ] !!! 14 0000000000000000000000000000000000000000000000000000000000000000
*** [ 20:00:00 | main ] FIRING WATCH 5 1
(o) [ 20:00:00 | main ] Pending transactions changed!
(o) [ 20:00:00 | main ] refreshPending()
(o) [ 20:00:00 | main ] refreshAccounts()
*** [ 20:00:00 | main ] FIRING WATCH 6 1
(o) [ 20:00:00 | main ] Blockchain changed!
(o) [ 20:00:00 | main ] refreshBlockCount()
(o) [ 20:00:00 | main ] refreshBlockChain()
(o) [ 20:00:00 | main ] refreshAccounts()
(o) [ 20:00:00 | main ] refreshBalances()
*** [ 20:00:00 | main ] FIRING WATCH 12 1
(o) [ 20:00:00 | main ] Pending transactions changed!
(o) [ 20:00:00 | main ] refreshPending()
(o) [ 20:00:00 | main ] refreshAccounts()
*** [ 20:00:00 | main ] FIRING WATCH 13 1
(o) [ 20:00:00 | main ] Blockchain changed!
(o) [ 20:00:00 | main ] refreshBlockCount()
(o) [ 20:00:00 | main ] refreshBlockChain()
(o) [ 20:00:00 | main ] refreshAccounts()
(o) [ 20:00:01 | main ] refreshBalances()
*** [ 20:00:01 | <unknown> ] FIRING WATCH 14 1
(o) [ 20:00:01 | <unknown> ] FFF (@{ 4aded1dc0263ecf564f56f3f85a6972a34da2f30 }#[{ c4b9b7c27f76495cba1c3f7385876a37d9c06244d8763fe42a9a47147f9b1c91 },{},{},{}]>0-4294967295< ) cad68953…
(o) [ 20:00:01 | <unknown> ] +++ 15 cad68953…
--- [ 20:00:02 | main ] Looking up NatSpec: 1591a978… 
*** [ 20:00:02 | main ] Skipping confirmation step for: DANGEROUS! Unknown Contract Transaction! 
 ÐApp is attempting to call into an unknown contract at address .

Call involves sending 0 wei to the recipient, with additional network fees of up to 12000 finneyHowever, this also does other stuff which we don't understand, and does so in your name.

WARNING: This is probably going to cost you at least 12000 finney, however this doesn't include any side-effects, which could be of far greater importance.

REJECT UNLESS YOU REALLY KNOW WHAT YOU ARE DOING!
--- [ 20:00:02 | main ] startWorking for thread eth
*** [ 20:00:02 | main ] New transaction {4aded1dc…/1$0+1200000@10000000000000<-909a6c43… #4}
/S/ [ 20:00:02 | eth ] Paying 12000 finney from sender for gas ( 1200000 gas at 10000 Gwei )
*** [ 20:00:02 | eth ] Additional transaction ready: Restarting mining operation.
*** [ 20:00:02 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000, 696f7f71c3262aeabc1628dc1497582d6084ecef2c51bec61dde0faf155d3175, cad6895387ebcd8654ade531c52fc8f37860acbb6ff04187a4232e9d01493164 } )
(o) [ 20:00:02 | eth ] !!! 5 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:02 | eth ] !!! 11 696f7f71c3262aeabc1628dc1497582d6084ecef2c51bec61dde0faf155d3175
(o) [ 20:00:02 | eth ] !!! 12 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:02 | eth ] !!! 14 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:02 | eth ] !!! 15 cad6895387ebcd8654ade531c52fc8f37860acbb6ff04187a4232e9d01493164
*** [ 20:00:03 | main ] FIRING WATCH 5 1
(o) [ 20:00:03 | main ] Pending transactions changed!
(o) [ 20:00:03 | main ] refreshPending()
(o) [ 20:00:03 | main ] refreshAccounts()
*** [ 20:00:03 | main ] FIRING WATCH 11 4
(o) [ 20:00:03 | main ] Our balances changed!
(o) [ 20:00:03 | main ] refreshBalances()
*** [ 20:00:03 | main ] FIRING WATCH 12 1
(o) [ 20:00:03 | main ] Pending transactions changed!
(o) [ 20:00:03 | main ] refreshPending()
(o) [ 20:00:03 | main ] refreshAccounts()
*** [ 20:00:03 | <unknown> ] FIRING WATCH 14 1
*** [ 20:00:03 | <unknown> ] FIRING WATCH 15 4
(o) [ 20:00:03 | <unknown> ] XXX 15
(o) [ 20:00:03 | <unknown> ] *X* cad6895387ebcd8654ade531c52fc8f37860acbb6ff04187a4232e9d01493164 : (@{ 4aded1dc0263ecf564f56f3f85a6972a34da2f30 }#[{ c4b9b7c27f76495cba1c3f7385876a37d9c06244d8763fe42a9a47147f9b1c91 },{},{},{}]>0-4294967295< )
*** [ 20:00:16 | miner-2 ] Completed 7c34443d… 409ae4df… 131072 1
--- [ 20:00:16 | miner-2 ] Completing mine!
*** [ 20:00:16 | miner-2 ] Mined fa46d920… (parent: 455ea9dc… )
=B= [ 20:00:16 | eth ] Attempting import of fa46d920… ...
/S/ [ 20:00:16 | eth ] Paying 12000 finney from sender for gas ( 1200000 gas at 10000 Gwei )
--- [ 20:00:16 | eth ] treeRoute 455ea9dc… ... fa46d920…
--- [ 20:00:16 | eth ] treeRoute 8 ... 9
--- [ 20:00:16 | eth ] to: 8 fa46d920…
=B= [ 20:00:16 | eth ]    Imported and best 1310720 . Has 0 siblings. Route: [ fa46d920…, ]
*** [ 20:00:16 | eth ] New block on chain: Restarting mining operation.

************************************* WEIRD PART *************************************

/S/ [ 20:00:16 | eth ] Invalid Nonce: Require 2  Got 1
*** [ 20:00:16 | eth ] Dropping invalid transaction:
*** [ 20:00:16 | eth ] /home/androlo/cpp-ethereum/libethereum/Executive.cpp(96): Throw in function void dev::eth::Executive::initialize(const dev::eth::Transaction&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InvalidNonce>
std::exception::what: std::exception
[dev::tag_required*] = 2
[dev::tag_got*] = 1

********************************************************************************************

*** [ 20:00:16 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000, 0000000000000000000000000000000000000000000000000000000000000001, 696f7f71c3262aeabc1628dc1497582d6084ecef2c51bec61dde0faf155d3175 } )
(o) [ 20:00:16 | eth ] !!! 5 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:16 | eth ] !!! 6 0000000000000000000000000000000000000000000000000000000000000001
(o) [ 20:00:16 | eth ] !!! 11 696f7f71c3262aeabc1628dc1497582d6084ecef2c51bec61dde0faf155d3175
(o) [ 20:00:16 | eth ] !!! 12 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 20:00:16 | eth ] !!! 13 0000000000000000000000000000000000000000000000000000000000000001
(o) [ 20:00:16 | eth ] !!! 14 0000000000000000000000000000000000000000000000000000000000000000
*** [ 20:00:16 | main ] FIRING WATCH 5 1
(o) [ 20:00:16 | main ] Pending transactions changed!
(o) [ 20:00:16 | main ] refreshPending()
(o) [ 20:00:16 | main ] refreshAccounts()
```

Some output from node app to show that things works.
```
  sUnit
    #test
Loading files.
[ 'unit_test' ]
[ 'unit_test' ]
pushcreate: unit_test
Starting deployment.
Block number at start: 7
Deploying: unit_test
Address: 0x4aded1dc0263ecf564f56f3f85a6972a34da2f30
null             <-- these are the 'pending' watches failing.
[]
null
[]
New block: 8
Contract was added to chain.
info: [Test] Starting solidity contract tests
null
[]
*********************** These all depend on solidity event watches ****************
info: [Test] Running 1 out of 3
success: [Test] PASSED: Test 'testString'.
info: [Test] Running 2 out of 3
success: [Test] PASSED: Test 'testInt'.
info: [Test] Running 3 out of 3
success: [Test] PASSED: Test 'testMapping'.
success: [Test] *** All tests PASSED. ***
      ✓ Should deploy and succesfully test the unit_test.sol contract' (8573ms)

  1 passing (9s)

```

**Comment by caktux** [comment] 2015-04-01 21:14
Also getting nonce errors for every transaction, looks like it was introduced in b0f2254

**Comment by gavofyork** [comment] 2015-04-02 16:24
there's nothing in b0f2254 that suggests it has anything to do with this. can you give full and clear instructions for reproduction?

**Comment by caktux** [comment] 2015-04-02 16:26
https://build.ethdev.com/builders/Linux%20C%2B%2B%20integration/builds/679

**Comment by caktux** [comment] 2015-04-02 17:54
Using `eth_sendTransaction` to create a contract, you get the errors mentioned above. Reverting a060841 on top of latest develop fixes those nonce errors, and reverting 1d4e611 fixes transactions getting dropped (I'd say randomly but it was dropping the same transaction every time on the build server). Since this has nothing to do with how those transactions are created and sent, it means there's other things internally depending on those number representations.

**Comment by ethers** [comment] 2015-04-02 21:57
on develop 54f20f1 I am also seeing a number of these in the log:

cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

**Comment by ethers** [comment] 2015-04-03 01:38
I am also seeing dropped transactions (don't know what the cause is) since 2 days ago.

**Comment by gavofyork** [comment] 2015-04-03 17:31
so the only thing that a060841 touched was the `eth_getCode` and the only time it altered its result was in substituting `"0x00"` to `"0x"` (correct according to the new tests). I can't imagine how a minor aspect of `eth_getCode` would be related to nonce errors.

1d4e611 is somewhat lower level; and fixes the presentation of numbers in JS by removing the leading zero. nonetheless, this code isn't used for anything inside ethereum's core.

furthermore, the invalid nonce/dropping transaction you're seeing is completely normal behaviour - it's simply dropping the transaction from the transaction pool because the nonce is *no longer* valid (probably because it has been mined into the current state, but potentially because one with the same nonce from the same account has been mined; we don't make the distinction). there's nothing per se wrong with the logs you've presented.

**Comment by caktux** [comment] 2015-04-04 03:42
You're right, the nonce errors aren't related and started sooner than that, now tracking down which commit introduced them. As Andreas was saying, the transactions aren't actually getting dropped, which is misleading since we get the error message when it's actually not what's happening. Turns out it was timing out because pyepm was comparing the hex result of `eth_getTransactionCount`, converting that to long integers obviously solved that, my bad on this one, those commits merely brought up something that would've broken eventually. Since we need to wait for the transaction count to be incremented as you explained in #1136, that is what it is waiting for to send the next transaction.

So, the issue is really only those misleading nonce errors.

**Comment by caktux** [comment] 2015-04-04 03:54
Nonce errors introduced in 25333ca, showing up in [integration build #621](https://build.ethdev.com/builders/Linux%20C%2B%2B%20integration/builds/621). See [post-deployment eth.log](https://build.ethdev.com/builders/Linux%20C%2B%2B%20integration/builds/621/steps/start-eth-test/logs/eth.log). All previously successful builds were fine.

**Comment by gavofyork** [comment] 2015-04-06 15:28
Fixed in latest.

**Closed by gavofyork** 2015-04-06 15:28 UTC
Labels: core, enhancement
