### ISSUE TITLE
Aleth Stable/Dev Crashes on "Go" Connect (Win7 x64)

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/cpp-ethereum#1173] opened 2015-03-02 03:49 UTC
Run in admin, w/ virus software off, roaming/ethereum cleared, MSVC x86 installed. Aleth boots fine, but the second I hit "Connect to Network" or "Go" I get a "alethzero.exe has stopped working". Feels like QT, is this normal or to be expected at this stage?

**Comment by subtly** [comment] 2015-03-20 22:38
This should be fixed now. Does it still crash w/latest develop? (Note: Go node isn't always available to connect)

**Comment by gavofyork** [comment] 2015-03-21 20:37
please test again on latest develop.

**Comment by debris** [comment] 2015-04-26 18:40
Cannot reproduce anymore. Please reopen if it still occurs.

**Closed by debris** 2015-04-26 18:40 UTC
Labels: unconfirmed
