### ISSUE TITLE
Core dump on latest develop

### ISSUE THREAD

**Issue by tymat** [ethereum/cpp-ethereum#2227] opened 2015-06-18 04:47 UTC
On 93fbd47c714eae991bf23f6fc89d209b1da2b1da
````
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 289855 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 291545 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 303030 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 310559 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 304878 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 311526 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 309598 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 305810 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 310559 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 310559 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 307692 blocks/s)
  ℹ  12:43:54|eth  100 blocks imported in 0 ms ( 293255 blocks/s)
eth: malloc.c:2373: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted (core dumped)

**Comment by LefterisJP** [comment] 2015-06-18 07:09
Can you build a debug build and try to provide a backtrace?

**Comment by nethyb** [comment] 2015-06-20 14:41
I'm also experiencing this issue: ( commit 47b6e38 on Ubuntu 14.04.2 LTS)

▣┅▶  14:33:40|p2p|304de4f1…|Geth/v0.9.31-4c2ba1af/linux/go1.4.2  OK - ready for chain insertion.
▣┅▶  14:33:40|p2p|304de4f1…|Geth/v0.9.31-4c2ba1af/linux/go1.4.2  Queuing block #0edae842… for import...
Press Entereth: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted (core dumped)

**Comment by chriseth** [comment] 2015-07-02 10:46
Can you upload the core dump somewhere together with the binary?

**Comment by chriseth** [comment] 2015-07-02 10:50
Possibly duplicate of #2161

**Comment by gavofyork** [comment] 2015-07-28 13:22
assumign duplicate.

**Closed by gavofyork** 2015-07-28 13:22 UTC
