### ISSUE TITLE
poc-8.ethdev.com json rpc is blocked

### ISSUE THREAD

**Issue by romanman** [ethereum/cpp-ethereum#936] opened 2015-02-03 11:14 UTC
it's not a code bug , because my local latest cpp code 
is working for json rpc but for POST to poc-8.ethdev.com
I get this: 

```
<html>
    <head>
        <title>Index of /</title>
        <style>th {text-align: left;}</style>
    </head>
    <body>
        <h1>Index of /</h1>
        <pre>
            <table cellpadding="0">
                <tr>
                    <th>
                        <a href="?nd">Name</a>
                    </th>
                    <th>
                        <a href="?dd">Modified</a>
                    </th>
                    <th>
                        <a href="?sd">Size</a>
                    </th>
                </tr>
                <tr>
                    <td colspan="3">
                        <hr>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/..">Parent directory</a>
                        </td>
                        <td>&nbsp;-</td>
                        <td>&nbsp;&nbsp;-</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/CMakeFiles/">CMakeFiles/</a>
                        </td>
                        <td>&nbsp;28-Jan-2015 16:18</td>
                        <td>&nbsp;&nbsp;[DIRECTORY]</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/Makefile">Makefile</a>
                        </td>
                        <td>&nbsp;06-Jan-2015 10:12</td>
                        <td>&nbsp;&nbsp;6.7k</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/cmake_install.cmake">cmake_install.cmake</a>
                        </td>
                        <td>&nbsp;06-Jan-2015 10:12</td>
                        <td>&nbsp;&nbsp;2.0k</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/eth">eth</a>
                        </td>
                        <td>&nbsp;29-Jan-2015 00:16</td>
                        <td>&nbsp;&nbsp;394.0k</td>
                    </tr>
                </table>
            </body>
        </html>

```

**Comment by jorisbontje** [comment] 2015-02-03 11:28
@romanman related issues:
#870 #882 #829 ethereum/ethereum.js#41

**Comment by sveneh** [comment] 2015-02-04 11:40
duplicate of #829

**Closed by sveneh** 2015-02-04 11:40 UTC
