### ISSUE TITLE
Investigate the resource usage of cpp-ethereum during recent attacks

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3322] opened 2016-09-30 18:34 UTC
This story is about investigating the resource usage and finding the bottlenecks that are causing trouble.

At the end of this story, new stories should be created to fix the problems that were found.

---

I have been syncing `cpp-ethereum` on Windows 10 and Linux (PureOS, based on Debian Stretch) for the past couple of days, and they have both now reached blocks where cpp-ethereum cannot cope with the processing.

My Windows box is a Surface Pro 3 with only 4GB of memory, dual-core i5 processor and a 128GB HDD drive.   It is stuck on block 1,929,668 but seems not to crash, but just hang.

My Linux box is a Purism Librem 15 with 16GB of memory, quad-core i7 processor and multiple SSDs.   It got to a much later block, but the whole system locks up when it gets to the bad block.   In one case the `eth` process was killed by the OS, but on the other two occasions everything just locked up and died and it needed to be rebooted.   `top` was showing huge CPU and memory load at the time of failure.

**Comment by bobsummerwill** [comment] 2016-10-01 00:20
Hmm.  So on restarting this time, it looks like my Linux box restarted the sync from scratch and is now past the problematic blocks and up to to HEAD.

**Comment by chriseth** [comment] 2016-10-04 20:55
Currently syncing, up to block 2377047 (only 3000 short of head) with only a single crash way back around 1000000.

Machine: 2-core Intel xeon E5, 2.4GHz with 8GB RAM, might be virtualized

**Comment by winsvega** [comment] 2016-10-05 17:16
Here the instruction on how to run attack tests on testeth 
https://justpaste.it/z0ss

**Comment by bobsummerwill** [comment] 2016-10-06 21:03
On my Linux box it looks like it is dying around block 2283502, or maybe a block or two later (the TTY log is pretty messy).   Hmm - maybe not, just took a long, long time there.

**Comment by bobsummerwill** [comment] 2016-10-06 21:03
Which of these tests are failing or succeeding for you, @winsvega?

**Comment by winsvega** [comment] 2016-10-11 20:06
@bobsummerwill 
tests update: 
**suicide issue
correct result: should fail due to the incorrect block. 
bad result: client crashes with OOM

**shanghailove 
should pass. but as seen recently it does not fully reproduce the situation of a real network. 
even though it has exact state of all the attacker contracts.

**Comment by chriseth** [comment] 2016-10-12 12:54
@bobsummerwill any insights yet about where exactly the issue is?

**Comment by bobsummerwill** [comment] 2016-10-12 15:32
No - I'm afraid not.

I'm planning to try to spend all day in the debugger today.

**Comment by chriseth** [comment] 2016-10-17 16:36
The problem with a transaction around block 2283416 is that it calls extcodesize of all wallet contracts created from mist. This requires an excessize amount of disk reads and also blows up `m_cache`. Fixing this issue is tracked in https://github.com/ethereum/cpp-ethereum/issues/3353

**Comment by chriseth** [comment] 2016-10-21 10:57
I'll rather close this. We have a pretty good impression already and several items to work on.

**Closed by chriseth** 2016-10-21 10:57 UTC
Labels: in progress
