### ISSUE TITLE
Build Error: ‘SHA3_512’ is deprecated

### ISSUE THREAD

**Issue by lsnk** [ethereum/cpp-ethereum#3232] opened 2016-08-29 02:50 UTC
I'm getting this mistake trying to build cpp-ethereum on Debian with libcrypto++ 5.6.3, how can I fix this?

```
[ 18%] Building CXX object libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o
/root/cpp-ethereum/libethash/sha3_cryptopp.cpp: In function ‘void SHA3_256(const ethash_h256_t*, const uint8_t*, size_t)’:
/root/cpp-ethereum/libethash/sha3_cryptopp.cpp:30:21: error: ‘SHA3_256’ is deprecated: SHA-3 will be changing in the future due to FIPS 202 finalization [-Werror=deprecated-declarations]
  CryptoPP::SHA3_256().CalculateDigest((uint8_t*)ret, data, size);
                     ^
In file included from /root/cpp-ethereum/libethash/sha3_cryptopp.cpp:23:0:
/usr/local/include/cryptopp/sha3.h:60:7: note: declared here
 class SHA3_256 : public SHA3
       ^~~~~~~~
/root/cpp-ethereum/libethash/sha3_cryptopp.cpp: In function ‘void SHA3_512(uint8_t*, const uint8_t*, size_t)’:
/root/cpp-ethereum/libethash/sha3_cryptopp.cpp:35:21: error: ‘SHA3_512’ is deprecated: SHA-3 will be changing in the future due to FIPS 202 finalization [-Werror=deprecated-declarations]
  CryptoPP::SHA3_512().CalculateDigest(ret, data, size);
                     ^
In file included from /root/cpp-ethereum/libethash/sha3_cryptopp.cpp:23:0:
/usr/local/include/cryptopp/sha3.h:84:7: note: declared here
 class SHA3_512 : public SHA3
       ^~~~~~~~
cc1plus: all warnings being treated as errors
libethash/CMakeFiles/ethash.dir/build.make:134: recipe for target 'libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o' failed
make[2]: *** [libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o] Error 1
CMakeFiles/Makefile2:305: recipe for target 'libethash/CMakeFiles/ethash.dir/all' failed
make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by bobsummerwill** [comment] 2016-08-29 04:06
That is really spooky, @lsnk!

I am working through **exactly** that same issue in my ARM cross-builds right now, and am typing a comment on exactly the root cause as we speak :-)

I suspect that you actually have a version of libcrypto++ which is actually a little ahead of the 5.6.3 release.

How did you get that install?   Did you use `scripts/install_deps.sh`?   If not, please do :-)

Here's why ... https://github.com/doublethinkco/cpp-ethereum-cross/blob/952f6be5ce64dccc2b017996e17d7bbf30af6c02/cross-build/ethereum/setup.sh#L50

**Comment by bobsummerwill** [comment] 2016-08-29 04:08
See https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/install_deps.sh#L243.

Which Debian version are you using?   Stretch?   If so, maybe the 5.6.3 you get there is subtly different than the source in the ZIP?

**Comment by lsnk** [comment] 2016-08-29 04:17
Yeah, probably git version is not good now, I've got Stretch and install script is only suitable for Jessie so I decided to compile libcrypto++ from git sources. Will see if https://www.cryptopp.com/cryptopp563.zip works.

**Comment by bobsummerwill** [comment] 2016-08-29 04:40
Right - if you are using master from git then it won't work right now, for sure.

That is my exact same scenario, though I want to add a suitably targeted pragma around that site in cpp-ethereum, so that it will work.   Will keep you in the loop.

"install script is only suitable for Jessie"

^ Please could you elaborate?   It's only been tested on Jessie, but I want it to work for Wheezy and Stretch too.    What is not working for you?   Let's fix it.

**Comment by bobsummerwill** [comment] 2016-08-30 05:56
See https://github.com/ethereum/cpp-ethereum/pull/3239.

Please could you elaborate on the issues you were hitting with `install_deps.sh`?  Thanks!

**Comment by lsnk** [comment] 2016-08-30 06:07
I've succesfully built cpp-ethereum but ethminer seems to miss some boost libraries.

`error while loading shared libraries: libboost_regex.so.1.58.0: cannot open shared object file: No such file or directory`

**Comment by bobsummerwill** [comment] 2016-08-30 06:20
The Boost versions will need to match.    It will be looking for different `.so` filenames.

Are you sure that you don't have `boost-1.58.0` installed too?   You must have, I think, and those will be the ones which you have installed.

Please could you answer my question about `install_deps.sh`?    Our path to a good solution for everybody here is to get that working, so it fixes your problems, and then locks that solution into the codebase itself.

**Comment by lsnk** [comment] 2016-08-30 06:26
The script just exits on my Debian Stretch here: https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/install_deps.sh#L209

So I made all steps manually, would you like me to correct a script part for just Stretch?

**Comment by bobsummerwill** [comment] 2016-08-30 06:50
"I've rebuilt ethereum after reinstalling boost libraries, evertything is ok now."

Great!

"The script just exits on my Debian Stretch here"

Ah!   I had forgotten that there were the hard `exit`s.

Please could you just try removing L209, and letting it run through the Debian steps below?   There were written-and-tested for Jessie, but I doubt they will need to be significantly altered for Stretch.

**Comment by bobsummerwill** [comment] 2016-08-31 11:27
This root issue was fixed yesterday, so I will close this issue:
https://github.com/ethereum/cpp-ethereum/pull/3239

Happy to keep chatting here about Stretch and `install_deps.sh`, if you have capacity!

CC @blockchaindev.

**Closed** 2016-08-31 11:28 UTC
Labels: bug
