### ISSUE TITLE
 std::bad_alloc

### ISSUE THREAD

**Issue by romanman** [ethereum/cpp-ethereum#2083] opened 2015-06-03 18:09 UTC
another crash got today: 
commit 2cd1b68333667669f86d4b31c200835410c69fa4
```
     Imported and best 102726145344  (# 67430 ). Has 0 siblings. Route: [#e13b167aג¦, #34e2db3dג¦]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by LefterisJP** [comment] 2015-06-03 18:55
We would need a complete backtrace. Please compile in debug mode and run it from inside gdb. When the segfault reoccurs type `bt` and send us the stack trace.

**Comment by romanman** [comment] 2015-06-04 06:16
@LefterisJP : always have `DEBUG=1`  , but never used `gdb`, 
so can you please give me the concrete orders

**Comment by LefterisJP** [comment] 2015-06-04 07:20
It's quite easy. Just write: 
```gdb --args EXECUTABLE_NAME ARG1 ARG2 ...``` which in your case would be the eth executable with whatever arguments you started it with.

**Comment by romanman** [comment] 2015-06-04 08:51
```
gdb --args ./eth --upnp off --bootstrap --peers 50 --remote 52.16.188.185:30303 --mining off  -j --json-rpc-port 8080 -v 5 --listen-port 30903  -d peer-1 --master roman
```

that's my command line and after running that 
I get : 

```
Type "apropos word" to search for commands related to "word".
Command name abbreviations are allowed if unambiguous.
(gdb)

```

**Comment by LefterisJP** [comment] 2015-06-04 08:56
My bad. There is more to write.

So now you are in the debugger prompt. Type `run`. This will start the program with the specified arguments inside the debugger.

Whenever the std::bad_alloc happens (or any other segfault) you will be notified. Then type `bt`. This will provide us with a stack trace.

**Comment by romanman** [comment] 2015-06-04 08:57
:+1: running

**Comment by romanman** [comment] 2015-06-04 09:29
```
[Thread 0x7fffdaffe700 (LWP 20042) exited]
[Thread 0x7fffe8eaa700 (LWP 20041) exited]
[Thread 0x7fffea2ce700 (LWP 20039) exited]
[Thread 0x7fffeaacf700 (LWP 20038) exited]
[Thread 0x7fffeb5e8700 (LWP 20037) exited]
[Thread 0x7fffeb73f780 (LWP 20033) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) bt
No stack.

```

Helps you ?

**Comment by LefterisJP** [comment] 2015-06-04 09:35
No because this is not a segfault. Did you by any chance send a SIGKILL (Ctrl-c Ctrl-c) to it? This is what the above seeems to indicate.

**Comment by romanman** [comment] 2015-06-04 09:35
@LefterisJP : nop not at all

**Comment by romanman** [comment] 2015-06-04 09:41
@LefterisJP : started that again , let's see how that will fail now

**Comment by LefterisJP** [comment] 2015-06-04 09:46
Can you post a little bit more info? Bigger output maybe? Something immediately kills the process from what it seems. We need to find out what.

**Comment by romanman** [comment] 2015-06-04 09:47
I am running it again (after changing pw to that linux), 
let's if that run will fail the same

**Comment by romanman** [comment] 2015-06-04 10:34
```
pipe
ג§ ג  06:07:52|p2p|3b3bd5cdג¦|Geth/v0.9.26/linux/go1.4.2  Closing peer session :-(
ג§ ג  06:07:52|p2p|3b3bd5cdג¦|Geth/v0.9.26/linux/go1.4.2  Aborting Sync :-(
ג§ ג  06:07:52|p2p|befb7bc7ג¦|Geth/v0.9.26-86103149/linux/go1.4.2  Error sending: Broken pipe
ג§ ג  06:08:26|p2p|befb7bc7ג¦|Geth/v0.9.26-86103149/linux/go1.4.2  Closing peer session :-(
ג§ ג  06:08:26|p2p|befb7bc7ג¦|Geth/v0.9.26-86103149/linux/go1.4.2  Aborting Sync :-(
ג§ ג  06:08:57|p2p|c296c1f2ג¦|++eth/v0.9.23/Release/Linux/g++/int  Error sending: Broken pipe
ג§ ג  06:08:59|p2p|c296c1f2ג¦|++eth/v0.9.23/Release/Linux/g++/int  Closing peer session :-(
ג§ ג  06:08:59|p2p|c296c1f2ג¦|++eth/v0.9.23/Release/Linux/g++/int  Aborting Sync :-(
[Thread 0x7fffd8a3d700 (LWP 20234) exited]
[Thread 0x7fffe8cb3700 (LWP 20233) exited]
[Thread 0x7fffea0d7700 (LWP 20231) exited]
[Thread 0x7fffea8d8700 (LWP 20230) exited]
[Thread 0x7fffeb45b700 (LWP 20229) exited]
[Thread 0x7fffeb73f780 (LWP 20225) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) bt
No stack.
(gdb)
```

the same :/

**Comment by LefterisJP** [comment] 2015-06-04 10:58
I see. If you did not kill it yourself with a SIGKILL message then that means that for some reason your kernel kills it. This is in Ubuntu? Check your syslog `/var/log/syslog` for any reasons that the OS killed your application. It could have strained the system's resources too much (ran out of memory) and as a result gotten killed.

**Comment by romanman** [comment] 2015-06-04 16:12
```
ג¶  07:42:49|p2p|fba39c7cג¦|Geth/v0.9.26/linux/go1.4.2  OK - queued for future [ 1433418173 vs 1433418169 ] - will wait until 07:42:53
ג§ ג  07:42:50|p2p|f461e779ג¦|Geth/v0.9.25-9f467c38/linux/go1.4.2  NewBlock: #58dbd433ג¦
ג£ג
ג¶  07:42:50|p2p|f461e779ג¦|Geth/v0.9.25-9f467c38/linux/go1.4.2  Queuing block #58dbd433ג¦ for import...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffeb4e7700 (LWP 20619)]
0x00007ffff516bcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff516bcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff516f0d8 in __GI_abort () at abort.c:89
Cannot access memory at address 0x7fffeb4e6e68
```


got better info now :+1:

**Comment by LefterisJP** [comment] 2015-06-04 17:00
That's memory access exception inside the standard library. Does not really help. It all points to problem with your OS. Can you scour the logs as I suggested above to see if something happens when you see this exception? 

Also next time try "thread apply all bt" to get trace of all threads.

**Comment by romanman** [comment] 2015-06-04 17:23
/var/log/syslog

http://pastebin.com/raw.php?i=tWFiSG5G

**Comment by LefterisJP** [comment] 2015-06-04 18:22
what kind of machien is this? Is it a VM? How much memory does the system have? The Out of memory killer is invoked.

**Comment by romanman** [comment] 2015-06-04 18:25
```
root@poc-9-test:/home/cpp-full/cpp-ethereum/build/eth# uname -a
Linux poc-9-test 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
It's a Digital Ocean machine with 2GB RAM.

**Comment by LefterisJP** [comment] 2015-06-04 18:29
Even though you are not mining, I still think that 2GB is not enough. Depends on what else consumes memory on your system. Try with at least 4.

**Comment by romanman** [comment] 2015-06-04 18:34
@LefterisJP : no mining and nothing else is running, 
never have such a problem on that type of machine
is it connected somehow to latest changes ?

**Comment by romanman** [comment] 2015-06-05 10:12
@LefterisJP : running on `4gb` now 
the usage is `2.5gb` do you think 
there should some good investigation
for the reason of that memory waste jump ?

**Comment by LefterisJP** [comment] 2015-06-05 10:41
Yes there is. We have some issues with the network where it tries to download so many blocks parallely and it runs out of memory. This will be fixed with the new version of networking (PV61). The problem is tht this will be a network change and all implementations should follow. So it will be probably be a bit of time until we start using it.

**Comment by romanman** [comment] 2015-06-05 10:41
@LefterisJP : cool so I think that one , can 
be close , cause it's very stable on `2.5g` of RAM

**Closed** 2015-06-05 10:45 UTC
