### ISSUE TITLE
unable or long time to stop eth miner

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1535] opened 2015-04-07 00:40 UTC
on develop 3525a62 and a6a1aa4 I started noticing that stopping eth is taking a long time with ctrl-c.  Here is example where even ctrl-c is not stopping the miner

```
-N- [ 17:32:04 | p2p ] Hello: Geth/v0.9.6/linux/go1.4.2 V[ 3 ] 672f8338… (eth,60)(shh,2) 0
-N- [ 17:32:04 | p2p |  0 ] Transition! State from Nothing , holding 
*N* [ 17:32:04 | p2p ] p2p.host.peer.register 672f8338…
-N- [ 17:32:04 | p2p | 27 ] Disconnect (reason: Peer had too many connections. )
-N- [ 17:32:04 | p2p | -1 ] Closing Peer Session :-(
-N- [ 17:32:04 | p2p |  0 ] Aborting Sync :-(
^C--- [ 17:32:06 | main ] stopWorking for thread p2p
--- [ 17:32:06 | main ] Stopping p2p
--- [ 17:32:06 | p2p ] Finishing up worker thread
--- [ 17:32:06 | p2p ] stopWorking for thread ethsync
--- [ 17:32:06 | p2p ] Stopping ethsync
--- [ 17:32:06 | ethsync ] Finishing up worker thread
--- [ 17:32:06 | p2p ] Stopped ethsync
--- [ 17:32:06 | p2p ] stopWorking for thread anon
--- [ 17:32:06 | p2p ] Stopping anon
--- [ 17:32:06 | anon ] Finishing up worker thread
--- [ 17:32:06 | p2p ] Stopped anon
!N! [ 17:32:06 | p2p | -1 ] Error reading: Operation canceled
-N- [ 17:32:06 | p2p | -1 ] Closing Peer Session :-(
-N- [ 17:32:06 | p2p |  0 ] Aborting Sync :-(
--- [ 17:32:06 | main ] Stopped p2p
--- [ 17:32:06 | main ] stopWorking for thread eth
--- [ 17:32:06 | main ] Stopping eth







^C^C^C
^C^C


^C^C^C


*** [ 17:38:05 | miner-2 ] Completed 6da46b53… 817d112a… 1513666 1
--- [ 17:38:05 | miner-2 ] Completing mine!
*** [ 17:38:05 | miner-2 ] Mined f285d9da… (parent: 0ceba9d1… )




^C
*C* [ 17:39:50 | eth ] Safely dropping transaction 598497868b2f09266f09ee8a7e5e714240ad74043c7891db68a77bb1c8778904
*C* [ 17:39:50 | eth ] Safely dropping transaction b67b290602be78267bc9e0ea184c5c8f0e29e518bd8ebb4b687b3afad7d4ec5c
*C* [ 17:39:50 | eth ] Safely dropping transaction ad004b7056d088350cb2bb96a07832a76c5691299b13d405b4848484c082f3a6
*C* [ 17:39:50 | eth ] Safely dropping transaction f2b79f169d96e8faaa5644039f3129ccffbcdf6751a3b6100d64a6ea48007ea4
*C* [ 17:39:50 | eth ] Safely dropping transaction 2881a4b76737a5afa63809f5964b2db9e879940f5bf14504e64a05af9f130d15
*C* [ 17:39:50 | eth ] Safely dropping transaction c325cbef8aba3bbb366fe6a15939e70964b73a4c87fa8f7577adeaf05ce6b6b3
*C* [ 17:39:50 | eth ] Safely dropping transaction 2456d5c757faab03a5df7adb156f5bb23efe83eeceae8ac98c643be3dd6b9a6b
*C* [ 17:39:50 | eth ] Safely dropping transaction d50fc93e567584d4b19e1372f67d0f03ba981aacd0b75910d055fff4f5b08b66
*C* [ 17:39:50 | eth ] Safely dropping transaction 4f40cae800c0b6f5ba680718a291435227a934e082eb96c10346bd76953113ce
*C* [ 17:39:50 | eth ] Safely dropping transaction 0cd9b82c33261ba85d963d2ed31914dfadbaa94c0a0d906d4fa9aa3519027a23
*C* [ 17:39:50 | eth ] Safely dropping transaction f290e6c8e2db85a62b6ec1056c836e0c2b8a3f00f33afd03ab0302f485fbde16
*C* [ 17:39:50 | eth ] Safely dropping transaction 24546c087d2ab0279d1356fd57f1ac563e4ed3dc2afe373b137139395baf1245
*C* [ 17:39:50 | eth ] Safely dropping transaction 8eb612d1b359759fed7c079b4fe315a063884fdcb91aefe4fd6b2abd303aed50
*C* [ 17:39:50 | eth ] Safely dropping transaction 9849443312d9fc40b716e919c3f65a9d4c47cdcdfd2e1de9d88a80cce7ee0c67
*C* [ 17:39:50 | eth ] Safely dropping transaction 130f4bf36583e0567e83f99db4779ca97b13f674c2ddd7ee62dee0ac613c3307
*C* [ 17:39:50 | eth ] Safely dropping transaction c4ea8ac8d474aca1e08719a4777a2ac9c71553eac3c62a4dc324b53a990f9622
*C* [ 17:39:50 | eth ] Safely dropping transaction e3b52a6e676f87b476cb447467d8f79e6ecf83686006c71305b9691158907a70
*C* [ 17:39:50 | eth ] Safely dropping transaction c07cdc55bd019da2de4d35766b5941a45d6d456d7a26ee4b1661560e8c4ac88b
*C* [ 17:39:50 | eth ] Safely dropping transaction ca01213f959a901807ff1921d88bae84543a070207197e7a72855274775590c1
*C* [ 17:39:50 | eth ] Safely dropping transaction d81c746d1c7ebbb816e9888913016c1bb76b66a134b94ce50c1902b530b2ae39
*C* [ 17:39:50 | eth ] Safely dropping transaction bf412eedf46c4caebbc4826233e50b84f2b7c6372c27df202656fd41a07c466f
*C* [ 17:39:50 | eth ] Safely dropping transaction ad617062270bee4de099b7fd0f4e9bcc95938ffa9044d37ea4b59c69059f4a5b
*C* [ 17:39:50 | eth ] Safely dropping transaction cc3e36039c9b2e16c0f8695267cc10ca6ff181b9462b586d93cd7caf9ca612fa
*C* [ 17:39:50 | eth ] Safely dropping transaction 7c3d61fac309cd910960a8cd7c54aff4f1e0857096d8c10d155b93f1c45a8848
*C* [ 17:39:50 | eth ] Safely dropping transaction d7e2eafcb4174e6278889a2864f53e96508d2f04a7b47e4dddcfcf51f97d03ed
*C* [ 17:39:50 | eth ] Safely dropping transaction 2536c1f28f6358fa51d82697de2bbcf81358a9ee5da81fd546cecd4cc3b4d04c
*C* [ 17:39:50 | eth ] Safely dropping transaction 286203f789ea4c6ec2fb8aa62aebbf8435916937d68cf422932afd2c50baca0b
*C* [ 17:39:50 | eth ] Safely dropping transaction a95203af29cd7ab58b6f6e6cf3012a094e0b529f21bb82fd410bf60da2ead577
*C* [ 17:39:50 | eth ] Safely dropping transaction 3bdf5ee0139eb71810168c02eaea0e1d0193bc91aa3a8c9b65165f35225802ca
*C* [ 17:39:50 | eth ] Safely dropping transaction 1d956d6aeed489cec2a334e40b78151e576612b36e45b83e4e13da6f97eed3f4
*C* [ 17:39:50 | eth ] Safely dropping transaction be45513fda22a189a9f01a503382bff476f732ecab19f495820aec845442c1a8
*C* [ 17:39:50 | eth ] Safely dropping transaction b1aba708607c18180aac56f50e3f13612ef49cb83f7547a0187d538889fc93c5
*C* [ 17:39:50 | eth ] Safely dropping transaction b21c741e6c5b47ca7ac90aaca0e06b4026b4560d30f244cf37a689e434f6a616
*C* [ 17:39:50 | eth ] Safely dropping transaction dab0cbb2a8329608b1286bc31f774bf8d2ca351619fe54f0de25de3ad8144b63
*C* [ 17:39:50 | eth ] Safely dropping transaction 241844f32182ffb95ffbaa02c8aaba574f17035372b363eca6d40be24bd159c7
*C* [ 17:39:50 | eth ] Safely dropping transaction f03f60f6c7c9b4391957b1e56c4bbc7ef8d33580da6c8d823cef6470a806be9d
*C* [ 17:39:50 | eth ] Safely dropping transaction e2014b06853c2945e554005d95fc0ccd1f839bbc01703cfdb97ecd870eabde8c
*C* [ 17:39:50 | eth ] Safely dropping transaction b98b5a5cbc636806360f0a339e798cae756a090c4aa1a18c5bb0dc418b2db265
*C* [ 17:39:50 | eth ] Safely dropping transaction d9f5d9be34e4b7bfc2afa0aa23c87df5725958562e35c7804b54a7368ac7ceba
*C* [ 17:39:50 | eth ] Safely dropping transaction 49c58b79a9dc7b14c2781e85814de2f95be2bde8ceaec85992c8b6399cf0c58e
*C* [ 17:39:50 | eth ] Safely dropping transaction 902b1ccf191c401480b12635679ded66a83833255b712132545c94244f4c1de3
*C* [ 17:39:50 | eth ] Safely dropping transaction 0d91a5e56153c732a23c8ecd7dad593ae6fd514d0720cb878217e567a04a585a
*C* [ 17:39:50 | eth ] Safely dropping transaction 15a76c8ab1285867ba0ef66c1cd2603f6e9eb8a2158e4dc51df9c14f3738a4cb
*C* [ 17:39:50 | eth ] Safely dropping transaction c69330f366e3d9fc06a443101e828ae207008758458e45c6aa064a3d11d4bc7f
*C* [ 17:39:50 | eth ] Safely dropping transaction b218932edf3db46d4138ef86abfc4b5846f37f4afb094bcf365c6cc329dfe2ff
*C* [ 17:39:50 | eth ] Safely dropping transaction 7d2711fa33444abcbb140aa24bcaf9bc3f9f274493829423608641cb8903d4be
*C* [ 17:39:50 | eth ] Safely dropping transaction b0ad094dc1c28a330b11c29a5a84e6835a129462b2d879e3d28b623a612c382f
*C* [ 17:39:50 | eth ] Safely dropping transaction b303207c7b9b2a6b4355b2c89985472b513e2d83b7670ca4220eced8e0ffaa24
*C* [ 17:39:50 | eth ] Safely dropping transaction 886735a092f3597e0fe3b2da0a62aca68a491dbf96291a2aed8bc41b5287d39b
*C* [ 17:39:50 | eth ] Safely dropping transaction cfaf5a14a26c8fc3c60d8d5d0dd6016014d842ce735b2278e70186145ebe7655
*C* [ 17:39:50 | eth ] Safely dropping transaction 89e8f6139a2f5c28d9c4082ccc0220042babbbec8802dd7f02ff7222617a140e
*C* [ 17:39:50 | eth ] Safely dropping transaction 9703ddbb3fcd8ace2dec0bb57f9636b275e46a6089624cc77701f08c322fc37f
*C* [ 17:39:50 | eth ] Safely dropping transaction 27ab1dadea8f453ea480cd6047575c5a829078fdb6070b000024a682e8668c4b
*** [ 17:39:50 | eth ] New block on chain: Restarting mining operation.
*** [ 17:39:50 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000, 0000000000000000000000000000000000000000000000000000000000000001 } )
--- [ 17:39:50 | eth ] Finishing up worker thread
--- [ 17:39:50 | main ] Stopped eth
--- [ 17:39:50 | main ] stopWorking for thread miner-0
--- [ 17:39:50 | main ] Stopping miner-0
--- [ 17:39:50 | miner-0 ] Finishing up worker thread
--- [ 17:39:50 | main ] Stopped miner-0
--- [ 17:39:50 | main ] stopWorking for thread miner-0
--- [ 17:39:50 | main ] stopWorking for thread miner-1
--- [ 17:39:50 | main ] Stopping miner-1
--- [ 17:39:50 | miner-1 ] Finishing up worker thread
--- [ 17:39:50 | main ] Stopped miner-1
--- [ 17:39:50 | main ] stopWorking for thread miner-1
--- [ 17:39:50 | main ] stopWorking for thread miner-2
--- [ 17:39:50 | main ] Stopping miner-2
--- [ 17:39:50 | miner-2 ] Finishing up worker thread
--- [ 17:39:50 | main ] Stopped miner-2
--- [ 17:39:50 | main ] stopWorking for thread miner-2
--- [ 17:39:50 | main ] stopWorking for thread miner-3
--- [ 17:39:50 | main ] Stopping miner-3
--- [ 17:39:50 | miner-3 ] Finishing up worker thread
--- [ 17:39:50 | main ] Stopped miner-3
--- [ 17:39:50 | main ] stopWorking for thread miner-3
*** [ 17:39:50 | main ] Closing state DB
*** [ 17:39:50 | main ] Closing blockchain DB
--- [ 17:39:50 | main ] stopWorking for thread eth
--- [ 17:39:50 | main ] stopWorking for thread anon
--- [ 17:39:50 | main ] stopWorking for thread ethsync
--- [ 17:39:50 | main ] stopWorking for thread p2p
```

**Comment by gavofyork** [comment] 2015-04-07 20:08
probably a duplicate of #1492

**Closed by gavofyork** 2015-04-07 20:08 UTC
