### ISSUE TITLE
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" when launch Alethzero

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#2164] opened 2015-06-12 08:03 UTC
develop 3f94350

cmake cmd was:
``cmake .. -DCMAKE_BUILD_TYPE=Release -DFATDB=1 -DBUNDLE=full``

Run alethzero and the following keeps getting displayed (and no AZ window).  maybe the cause of #1820 ?

```
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]
Assertion failed:_kind == VMKind::Interpreter && "JIT disabled in build configuration" [func=static std::unique_ptr<dev::eth::VMFace> dev::eth::VMFactory::create(dev::eth::VMKind), line=60, file=cpp-ethereum/libevm/VMFactory.cpp]

```

**Comment by arkpar** [comment] 2015-07-02 10:56
can't reporduce, is this still the case?

**Comment by ethers** [comment] 2015-07-03 07:43
still got it on commit b3ff643
will rebuild with latest

**Comment by chfast** [comment] 2015-07-03 09:13
I can reproduce it. Sorry for that.

It is a simple AZ config problem. Config states to use JIT but our build of AZ does not have the JIT. Normally, you can turn it of and on in the menu: Special -> Use LLVM-EVM. But that is also disabled because your build does not have JIT.

The workaround is to open the config file ~/.config/ethereum/alethzero.conf and change "jitvm" to false (`jitvm=false`).

**Comment by chfast** [comment] 2015-07-03 13:49
Will be fixed by https://github.com/ethereum/cpp-ethereum/pull/2374.

**Closed** 2015-07-06 06:27 UTC
Labels: az, bug
