### ISSUE TITLE
Solidity clobbers values in memory

### ISSUE THREAD

**Issue by skmgoldin** [ethereum/cpp-ethereum#2840] opened 2015-08-15 23:36 UTC
In the following example, Solidity corrupts the value of `registeredOwners` in-memory (but not in storage!) on the line `newOwner.addr = _ownerAddr;` in the `addOwner` function. Uncommenting `uint garbage` in `struct Owner` resolves that particular instance of the issue, but there seem to be cascading effects--this type of error shows up again after consecutive invocations of `addOwner` seemingly no matter what.

```
contract Example {

  uint public registeredOwners;
  uint public inputsCount;
  uint public numOwners;
  bool public locked;
  Owner[3] owners;

  struct Owner {
    //uint garbage; 
    address addr;
    uint owed;
    uint lastCollectedTx;
  }

  function Example(uint _numOwners) {
    registeredOwners = 999;
    inputsCount = 999;
    locked = false;
    numOwners = _numOwners;
  }

  function addOwner(address _ownerAddr) public returns (bool) {
    if(locked) return false;
    Owner newOwner;
    newOwner.addr = _ownerAddr;
    newOwner.owed = 999;
    newOwner.lastCollectedTx = 999;

    if(registeredOwners == 999) {
      owners[0] = newOwner;
      registeredOwners = 1;
      return true;
    }

    owners[registeredOwners] = newOwner;
    registeredOwners = registeredOwners + 1;
    if(registeredOwners == numOwners) locked = true;
    return true;
  }
}
```

**Comment by chriseth** [comment] 2015-08-18 15:09
Duplicate of #2839

**Closed by chriseth** 2015-08-18 15:09 UTC
Labels: solidity
