### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' 

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#2501] opened 2015-07-16 22:20 UTC
Ubuntu 15.04.  8gb ram, core i3 (it's the mining rig from the tutorial)

Fresh install, never installed eth prior on that machine

eth -j -i -b was used to start

Climbs the chain up to 534608 then crashes with this log:

http://pastebin.com/3LjW1vFg

**Comment by chriseth** [comment] 2015-07-21 09:04
Do you still have the core dump file?

**Comment by chriseth** [comment] 2015-07-30 19:25
Closing as duplicate of #2646

**Closed by chriseth** 2015-07-30 19:25 UTC
Labels: moreinfoplease
