### ISSUE TITLE
solc can't upgrade ubuntu trusty

### ISSUE THREAD

**Issue by simpletechnology** [ethereum/cpp-ethereum#3031] opened 2016-08-11 12:44 UTC
hey guys, http://pastebin.com/fFK9T9UX, how do i fix this?

**Comment by bobsummerwill** [comment] 2016-08-11 19:02
Hey @simpletechnology,

This is a dupe of https://github.com/ethereum/solidity/issues/865.   Please head over there for an update!

**Closed by bobsummerwill** 2016-08-11 19:02 UTC
