### ISSUE TITLE
segfault when mining on OSX is back

### ISSUE THREAD

**Issue by caktux** [ethereum/cpp-ethereum#1668] opened 2015-04-18 12:09 UTC
```
backtrace:

#0  0x00007fff8fb30c41 in _pthread_join_cleanup () from /usr/lib/system/libsystem_pthread.dylib
No symbol table info available.
#1  0x00007fff8fb32bd5 in pthread_join () from /usr/lib/system/libsystem_pthread.dylib
No symbol table info available.
#2  0x00007fff85444ba0 in std::__1::thread::join() () from /usr/lib/libc++.1.dylib
No symbol table info available.
#3  0x0000000100d96224 in dev::Worker::stopWorking() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
No symbol table info available.
#4  0x00000001001c9273 in dev::eth::GenericMiner<dev::eth::Ethash>::setWork(dev::eth::Ethash::WorkPackage const&) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethereum.dylib
No symbol table info available.
#5  0x00000001001cce24 in dev::eth::GenericFarm<dev::eth::Ethash>::submitProof(dev::eth::Ethash::Solution const&, dev::eth::GenericMiner<dev::eth::Ethash>*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethereum.dylib
No symbol table info available.
#6  0x000000010066646c in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
No symbol table info available.
#7  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
No symbol table info available.
#8  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
No symbol table info available.
#9  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
No symbol table info available.
#10 0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
No symbol table info available.
#11 0x0000000000000000 in ?? ()
No symbol table info available.


registers:

rax            0x3	3
rbx            0x3	3
rcx            0xffffffff	4294967295
rdx            0x0	0
rsi            0x0	0
rdi            0x103b81000	4357361664
rbp            0x143d09790	0x143d09790
rsp            0x143d09770	0x143d09770
r8             0x0	0
r9             0x0	0
r10            0x0	0
r11            0x246	582
r12            0x103b81000	4357361664
r13            0x143d0a000	5432713216
r14            0x0	0
r15            0x0	0
rip            0x7fff8fb30c41	0x7fff8fb30c41 <_pthread_join_cleanup+66>
eflags         0x10206	[ PF IF RF ]
cs             0x2b	43
ss             <unavailable>
ds             <unavailable>
es             <unavailable>
fs             0x0	0
gs             0x0	0


current instructions:

=> 0x7fff8fb30c41 <_pthread_join_cleanup+66>:	mov    0x68(%r12),%rax
   0x7fff8fb30c46 <_pthread_join_cleanup+71>:	mov    0x70(%r12),%rcx
   0x7fff8fb30c4b <_pthread_join_cleanup+76>:	test   %rax,%rax
   0x7fff8fb30c4e <_pthread_join_cleanup+79>:	je     0x7fff8fb30c5b <_pthread_join_cleanup+92>
   0x7fff8fb30c50 <_pthread_join_cleanup+81>:	mov    %rcx,0x70(%rax)
   0x7fff8fb30c54 <_pthread_join_cleanup+85>:	mov    0x70(%r12),%rcx
   0x7fff8fb30c59 <_pthread_join_cleanup+90>:	jmp    0x7fff8fb30c62 <_pthread_join_cleanup+99>
   0x7fff8fb30c5b <_pthread_join_cleanup+92>:	mov    %rcx,-0x1c4739f2(%rip)        # 0x7fff736bd270
   0x7fff8fb30c62 <_pthread_join_cleanup+99>:	mov    %rax,(%rcx)
   0x7fff8fb30c65 <_pthread_join_cleanup+102>:	lea    -0x1c473994(%rip),%rdi        # 0x7fff736bd2d8
   0x7fff8fb30c6c <_pthread_join_cleanup+109>:	callq  0x7fff8fb3324c
   0x7fff8fb30c71 <_pthread_join_cleanup+114>:	test   %ebx,%ebx
   0x7fff8fb30c73 <_pthread_join_cleanup+116>:	jne    0x7fff8fb30cd7 <_pthread_join_cleanup+216>
   0x7fff8fb30c75 <_pthread_join_cleanup+118>:	test   %r14,%r14
   0x7fff8fb30c78 <_pthread_join_cleanup+121>:	je     0x7fff8fb30c99 <_pthread_join_cleanup+154>
   0x7fff8fb30c7a <_pthread_join_cleanup+123>:	mov    0x38(%r12),%rax


threads backtrace:

Thread 16 (Thread 0x1f03 of process 33368):
#0  0x000000010066d116 in ethash_hash () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#1  0x0000000100666304 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#2  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 15 (Thread 0x1e03 of process 33368):
#0  0x0000000100bce2e8 in CryptoPP::KeccakF1600(unsigned long long*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcrypto.dylib
#1  0x0000000100bce88c in CryptoPP::SHA3::TruncatedFinal(unsigned char*, unsigned long) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcrypto.dylib
#2  0x000000010066d322 in SHA3_256 () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#3  0x000000010066d218 in ethash_hash () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#4  0x0000000100666304 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#5  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#6  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#7  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#8  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#9  0x0000000000000000 in ?? ()

Thread 14 (Thread 0x1d03 of process 33368):
#0  0x000000010066d151 in ethash_hash () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#1  0x0000000100666304 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#2  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 13 (Thread 0x1c03 of process 33368):
#0  0x000000010066d151 in ethash_hash () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#1  0x0000000100666304 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#2  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 12 (Thread 0x1b03 of process 33368):
#0  0x000000010066d16f in ethash_hash () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#1  0x0000000100666304 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#2  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 11 (Thread 0x1a03 of process 33368):
#0  0x000000010066d151 in ethash_hash () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#1  0x0000000100666304 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#2  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 10 (Thread 0x1903 of process 33368):
#0  0x00007fff829bc3fa in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010076ae42 in MHD_select () from /usr/local/lib/libmicrohttpd.10.dylib
#2  0x000000010076c581 in MHD_select_thread () from /usr/local/lib/libmicrohttpd.10.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 9 (Thread 0x1803 of process 33368):
#0  0x00007fff829bc3fa in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010076ae42 in MHD_select () from /usr/local/lib/libmicrohttpd.10.dylib
#2  0x000000010076c581 in MHD_select_thread () from /usr/local/lib/libmicrohttpd.10.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 8 (Thread 0x1703 of process 33368):
#0  0x00007fff829bc3fa in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010076ae42 in MHD_select () from /usr/local/lib/libmicrohttpd.10.dylib
#2  0x000000010076c581 in MHD_select_thread () from /usr/local/lib/libmicrohttpd.10.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 7 (Thread 0x1603 of process 33368):
#0  0x00007fff829bc3fa in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010076ae42 in MHD_select () from /usr/local/lib/libmicrohttpd.10.dylib
#2  0x000000010076c581 in MHD_select_thread () from /usr/local/lib/libmicrohttpd.10.dylib
#3  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#4  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#5  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#6  0x0000000000000000 in ?? ()

Thread 6 (Thread 0x1503 of process 33368):
#0  0x00007fff829bc48a in __semwait_signal () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff8978ef5d in nanosleep () from /usr/lib/system/libsystem_c.dylib
#2  0x00007fff85444d28 in std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) () from /usr/lib/libc++.1.dylib
#3  0x0000000100d9631b in dev::Worker::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#4  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#5  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#6  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#7  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#8  0x0000000000000000 in ?? ()

Thread 5 (Thread 0x1403 of process 33368):
#0  0x00007fff829bc48a in __semwait_signal () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff8978ef5d in nanosleep () from /usr/lib/system/libsystem_c.dylib
#2  0x00007fff85444d28 in std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) () from /usr/lib/libc++.1.dylib
#3  0x0000000100d9631b in dev::Worker::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#4  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#5  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#6  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#7  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#8  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x1303 of process 33368):
#0  0x00007fff829bd21a in kevent () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010045d015 in boost::asio::detail::kqueue_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libp2p.dylib
#2  0x000000010045cc6c in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libp2p.dylib
#3  0x000000010045c8b5 in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libp2p.dylib
#4  0x000000010043ca45 in dev::p2p::Host::doWork() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libp2p.dylib
#5  0x0000000100d96324 in dev::Worker::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#6  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#7  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#8  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#9  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#10 0x0000000000000000 in ?? ()

Thread 3 (Thread 0x1203 of process 33368):
#0  0x00007fff829bc48a in __semwait_signal () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff8978ef5d in nanosleep () from /usr/lib/system/libsystem_c.dylib
#2  0x00007fff85444d28 in std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) () from /usr/lib/libc++.1.dylib
#3  0x0000000100d9631b in dev::Worker::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#4  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#5  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#6  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#7  0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#8  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x1113 of process 33368):
#0  0x00007fff8fb30c41 in _pthread_join_cleanup () from /usr/lib/system/libsystem_pthread.dylib
#1  0x00007fff8fb32bd5 in pthread_join () from /usr/lib/system/libsystem_pthread.dylib
#2  0x00007fff85444ba0 in std::__1::thread::join() () from /usr/lib/libc++.1.dylib
#3  0x0000000100d96224 in dev::Worker::stopWorking() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#4  0x00000001001c9273 in dev::eth::GenericMiner<dev::eth::Ethash>::setWork(dev::eth::Ethash::WorkPackage const&) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethereum.dylib
#5  0x00000001001cce24 in dev::eth::GenericFarm<dev::eth::Ethash>::submitProof(dev::eth::Ethash::Solution const&, dev::eth::GenericMiner<dev::eth::Ethash>*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethereum.dylib
#6  0x000000010066646c in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libethcore.dylib
#7  0x0000000100d963ff in void* std::__1::__thread_proxy<std::__1::tuple<dev::Worker::startWorking(dev::IfRunning)::$_0> >(void*) () from /usr/local/Cellar/cpp-ethereum/0.9.9-60-9/lib/libdevcore.dylib
#8  0x00007fff8fb2f268 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#9  0x00007fff8fb2f1e5 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#10 0x00007fff8fb2d41d in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#11 0x0000000000000000 in ?? ()

Thread 1 (Thread 0xf03 of process 33368):
#0  0x00007fff829bc3fa in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff818d5eb1 in _nc_timed_wait () from /usr/lib/libncurses.5.4.dylib
#2  0x00007fff818c95ea in _nc_wgetch () from /usr/lib/libncurses.5.4.dylib
#3  0x00007fff818c9d81 in wgetch () from /usr/lib/libncurses.5.4.dylib
#4  0x00007fff818c9f34 in wgetnstr () from /usr/lib/libncurses.5.4.dylib
#5  0x000000010000daaf in main ()
```

**Comment by gavofyork** [comment] 2015-04-20 08:19
duplicate of #1636

**Closed by gavofyork** 2015-04-20 08:19 UTC
Labels: bug
