### ISSUE TITLE
Core Dump Cannot assign requested address

### ISSUE THREAD

**Issue by aperseghin** [ethereum/cpp-ethereum#1398] opened 2015-03-24 14:15 UTC
output from running "eth" command 

Ethereum (++) 0.9.1
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
  Based on a design by Vitalik Buterin.

*N* [ 10:12:24 | main ] IP Address: 192.168.1.3  = [LOCAL]
*N* [ 10:12:24 | main ] Id: e5294826d69a56a77c77566691b11f6bb27ada72bc3d27d7fc8a780314360571bfcff71e18e1d31b2e0d7b92e0f299bb479f587ae40f9163295c17cbd43b419c
*** [ 10:12:24 | main ] Opened blockchain DB. Latest: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
*** [ 10:12:25 | main ] Opened state DB.
Transaction Signer: d134e55b80c02fd549534262f5764e3a1918e82e
Mining Benefactor: d134e55b80c02fd549534262f5764e3a1918e82e
*** [ 10:12:25 | eth ] New block on chain: Restarting mining operation.
*** [ 10:12:25 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
*** [ 10:12:29 | p2p ] UPnP device: http://192.168.1.1:2555/upnp/cbba0323-d2bb-3569-b2d2-2df8571c54c1/desc.xml [st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 ]
*N* [ 10:12:29 | p2p ] Punched through NAT and mapped local port 30303 onto external port 30303 .
*N* [ 10:12:29 | p2p ] External addr: 71.121.194.171
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  **what():  bind: Cannot assign requested address**
**Aborted (core dumped)**

**Comment by aperseghin** [comment] 2015-03-24 16:04
Results from compiled version of cpp-ethereum are the same as from the repo 

root@SERVER:~/ethereum/cpp-ethereum/build/eth# ./eth -a xxxxxxxxxxxxxxxxxxxxxx -m on 
!!! [ 11:10:36 | main ] /root/ethereum/cpp-ethereum/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = y

!!! [ 11:10:36 | main ] invalid hex character, coinbase rejected
!!! [ 11:10:36 | main ] /root/ethereum/cpp-ethereum/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = y

Ethereum (++) 0.9.1
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
  Based on a design by Vitalik Buterin.

*N* [ 11:10:36 | main ] IP Address: 192.168.1.3  = [LOCAL]
*N* [ 11:10:36 | main ] Id: xxxxxxxxxxxxxxxxxxxxxxxxx
*** [ 11:10:36 | main ] Opened blockchain DB. Latest: xxxxxxxxxxxxxxxxx
*** [ 11:10:36 | main ] Opened state DB.
--- [ 11:10:36 | main ] startWorking for thread eth
--- [ 11:10:36 | main ] Spawning eth
Transaction Signer: xxxxxxxxxxxxxxxxx
Mining Benefactor: xxxxxxxxxxxxxxxxx
--- [ 11:10:36 | main ] startWorking for thread p2p
--- [ 11:10:36 | main ] Spawning p2p
--- [ 11:10:36 | main ] startWorking for thread eth
--- [ 11:10:36 | main ] startWorking for thread miner-0
--- [ 11:10:36 | main ] Spawning miner-0
--- [ 11:10:36 | p2p ] startWorking for thread ethsync
--- [ 11:10:36 | p2p ] Spawning ethsync
--- [ 11:10:36 | p2p ] startWorking for thread anon
--- [ 11:10:36 | main ] startWorking for thread miner-1
--- [ 11:10:36 | main ] Spawning miner-1
--- [ 11:10:36 | p2p ] Spawning anon
*** [ 11:10:36 | eth ] New block on chain: Restarting mining operation.
*** [ 11:10:36 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
*** [ 11:10:36 | miner-0 ] Pre-reward stateRoot: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
*** [ 11:10:36 | miner-1 ] Pre-reward stateRoot: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
*** [ 11:10:39 | p2p ] UPnP device: http://192.168.1.1:2555/upnp/cbba0323-d2bb-3569-b2d2-2df8571c54c1/desc.xml [st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 ]
*N* [ 11:10:39 | p2p ] Punched through NAT and mapped local port 30303 onto external port 30303 .
*N* [ 11:10:39 | p2p ] External addr: 71.121.194.171
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Cannot assign requested address
Aborted (core dumped)
root@SERVER:~/ethereum/cpp-ethereum/build/eth#

**Comment by gavofyork** [comment] 2015-03-24 17:41
looks like a nat issue. for fast workaround, disable upnp detection: `./eth -n off`

**Comment by subtly** [comment] 2015-03-24 18:00
On it. UDP is trying to bind to the detected IP. (previously was binding to all IPs)

**Comment by aperseghin** [comment] 2015-03-24 18:37
great! i have recreated this same issue in multiple environments.

**Comment by chfast** [comment] 2015-03-24 19:45
I can confirm too. Disabling UPnP helps.

**Comment by subtly** [comment] 2015-03-30 09:00
This should be fixed in latest develop. Should work fine with or without UPnP. If local networking (connecting localhost to itself) is needed then consider using --listen-ip parameter.

@aperseghin Is this issue resolved with the latest develop?

**Closed** 2015-07-28 12:51 UTC
Labels: bug, network, showstopper
