### ISSUE TITLE
installation in Centos 6

### ISSUE THREAD

**Issue by farbodmahini** [ethereum/cpp-ethereum#3301] opened 2016-09-10 22:00 UTC
Hi
i use Centos6

and i have used this command : 
git clone --recursive https://github.com/ethereum/cpp-ethereum.git

and when i run this cm : ./scripts/install_deps.sh

this error displayed to me : 

[root@server cpp-ethereum]# ./scripts/install_deps.sh
./scripts/install_deps.sh: line 198: lsb_release: command not found
ERROR - Unsupported or unidentified Linux distro.
See http://cpp-ethereum.org/building-from-source/linux.html for manual instructions.
If you would like to get your distro working, that would be fantastic.
Drop us a message at https://gitter.im/ethereum/cpp-ethereum-development.

please help me ! how i can install this wallet in Centos6 ? 

thanks

**Comment by bobsummerwill** [comment] 2016-09-11 01:14
Hey there!

So, yes, you are only the second person to report having tried to build `cpp-ethereum` on CentOS, after @daniel-lucio.

- https://github.com/ethereum/cpp-ethereum/issues/3244
- https://github.com/ethereum/cpp-ethereum/issues/3250
- https://github.com/ethereum/cpp-ethereum/issues/3281

So I would be happy to work with Daniel and yourself to get this working, but I suspect from your last sentence that you are actually building the wrong project, because `cpp-ethereum` is an Ethereum client application, not a wallet.

The Ethereum wallet is http://github.com/ethereum/mist, though I doubt they have any CentOS support either.     So what exactly are you looking to do here?    Just to have a wallet to hold some Ether?   To mine?   To build dapps?    Are you a software developer?   Really to get your hands dirty and help add CentOS support to various of the tools in the Ethereum ecosystem?

I will close this as a duplicate of https://github.com/ethereum/cpp-ethereum/issues/3250.

Welcome :-)

**Closed by bobsummerwill** 2016-09-11 01:14 UTC
Labels: build-system

**Comment by daniel-lucio** [comment] 2016-09-11 21:50
@farbodmahini Currently I have done RPM's for Mageia. I will work on CentOS but you will need to be patient, there are many RPM's to do. My aim is to do it all by RPM's, no source at all.

**Comment by bobsummerwill** [comment] 2016-09-12 03:22
No rush, thanks, @daniel-lucio!

**Comment by daniel-lucio** [comment] 2016-09-12 04:24
First step done
http://inside-out.xyz/technology/libjson-rpc-cpp-0-6-0-rpm-for-centos-6-7.html

**Comment by daniel-lucio** [comment] 2016-09-15 16:15
Look:
[ 67%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Client.cpp.o
cd /builddir/build/BUILD/cpp-ethereum-develop/build/libethereum && /usr/bin/c++   -DDISABLE_BROKEN_UNIT_TESTS_UNTIL_WE_FIX_THEM -DETH_FATDB -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -Dethereum_EXPORTS -isystem /usr/include/jsoncpp -I/builddir/build/BUILD/cpp-ethereum-develop/build -I/builddir/build/BUILD/cpp-ethereum-develop/build/include -I/builddir/build/BUILD/cpp-ethereum-develop/libethereum/.. -I/builddir/build/BUILD/cpp-ethereum-develop/libethereum/../utils  -std=c++11 -fpermissive -fuse-ld=gold -DSTATICLIB -O2 -g -DETH_RELEASE -fPIC   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -o CMakeFiles/ethereum.dir/Client.cpp.o -c /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp: In member function 'void dev::eth::Client::onBadBlock(dev::Exception&) const':
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:140:51: error: no matching function for call to 'diagnostic_information(dev::Exception&, bool)'
   cwarn << boost::diagnostic_information(_ex, true);
                                                   ^
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:140:51: note: candidates are:
In file included from /usr/include/boost/exception/detail/exception_ptr.hpp:21:0,
                 from /usr/include/boost/exception_ptr.hpp:9,
                 from /usr/include/boost/thread/future.hpp:28,
                 from /usr/include/boost/thread.hpp:24,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/../libdevcore/Guards.h:30,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.h:34,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:22:
/usr/include/boost/exception/diagnostic_information.hpp:167:5: note: template<class T> std::string boost::diagnostic_information(const T&)
     diagnostic_information( T const & e )
     ^
/usr/include/boost/exception/diagnostic_information.hpp:167:5: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:140:51: note:   candidate expects 1 argument, 2 provided
   cwarn << boost::diagnostic_information(_ex, true);
                                                   ^
In file included from /usr/include/boost/exception_ptr.hpp:9:0,
                 from /usr/include/boost/thread/future.hpp:28,
                 from /usr/include/boost/thread.hpp:24,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/../libdevcore/Guards.h:30,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.h:34,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:22:
/usr/include/boost/exception/detail/exception_ptr.hpp:470:5: note: std::string boost::diagnostic_information(const boost::exception_ptr&)
     diagnostic_information( exception_ptr const & p )
     ^
/usr/include/boost/exception/detail/exception_ptr.hpp:470:5: note:   candidate expects 1 argument, 2 provided
make[2]: Leaving directory `/builddir/build/BUILD/cpp-ethereum-develop/build'
make[1]: Leaving directory `/builddir/build/BUILD/cpp-ethereum-develop/build'


RPM build errors:
make[2]: *** [libethereum/CMakeFiles/ethereum.dir/Client.cpp.o] Error 1
make[1]: *** [libethereum/CMakeFiles/ethereum.dir/all] Error 2
make: *** [all] Error 2


Is it a minimum release of boost? I am ussing 1.53

**Comment by bobsummerwill** [comment] 2016-09-15 16:28
Let's move to https://github.com/ethereum/cpp-ethereum/issues/3250.   This is a dupe of that.
