### ISSUE TITLE
`testeth` should emit an error when unrecognized fields are found in test fillers

### ISSUE THREAD

**Issue by jwasinger** [ethereum/cpp-ethereum#4428] opened 2017-08-30 18:55 UTC
Example filler: https://gist.github.com/jwasinger/7f8f507fdce3b6935ce556eea63d4b7f .
Note:
```
"6295ee1b4f6dd65047762f924ecd367c17eabf8f" : {
    "Nonce": 1
}
```

Current testeth output:
```
 ETHEREUM_TEST_PATH='/ethereum/tests' test/testeth -t StateTestsGeneral/stBadOpcode -- --singletest 'badOpcodes'  --filltests
Running 1 test case...
Test Case "stBadOpcode": 
50%...
100%

*** No errors detected
```

**Comment by axic** [comment] 2018-01-24 10:27
@winsvega this would be a good one to have

**Comment by axic** [comment] 2018-01-24 10:30
Duplicate of #4253?

**Comment by winsvega** [comment] 2018-01-24 10:49
already merged https://github.com/ethereum/cpp-ethereum/pull/4794

**Closed** 2018-01-24 11:40 UTC
