### ISSUE TITLE
undefined reference for neth

### ISSUE THREAD

**Issue by alphaonex86** [ethereum/cpp-ethereum#1504] opened 2015-04-02 22:59 UTC
Hello,

I have that's under gentoo:
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function nc::nc_window_streambuf::sync(): error: undefined reference to 'stdscr'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'cbreak'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'stdscr'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'wtimeout'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'keypad'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'stdscr'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'stdscr'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function form_dialog(std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, int, int, std::string): error: undefined reference to 'nodelay'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function form_dialog(std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, int, int, std::string): error: undefined reference to 'keypad'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function form_dialog(std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, int, int, std::string): error: undefined reference to 'wtimeout'
CMakeFiles/neth.dir/main.cpp.o:main.cpp:function form_dialog(std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >, int, int, std::string): error: undefined reference to 'wtimeout'
collect2: error: ld returned 1 exit status
neth/CMakeFiles/neth.dir/build.make:111: recipe for target 'neth/neth' failed
make[2]: *** [neth/neth] Error 1
CMakeFiles/Makefile2:1571: recipe for target 'neth/CMakeFiles/neth.dir/all' failed
make[1]: *** [neth/CMakeFiles/neth.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

Cheers,

**Comment by alphaonex86** [comment] 2015-04-02 23:02
Few line above:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/../../../../x86_64-pc-linux-gnu/bin/ld.gold: error: cannot find -lweb3jsonrpc
collect2: error: ld returned 1 exit status
libtestutils/CMakeFiles/testutils.dir/build.make:210: recipe for target 'libtestutils/libtestutils.so' failed
make[2]: *** [libtestutils/libtestutils.so] Error 1
CMakeFiles/Makefile2:1018: recipe for target 'libtestutils/CMakeFiles/testutils.dir/all' failed
make[1]: *** [libtestutils/CMakeFiles/testutils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by alphaonex86** [comment] 2015-04-02 23:02
With: cmake . -DJSONRPC=0 -DHEADLESS=1

**Comment by debris** [comment] 2015-04-02 23:32
fixed in #1494 .

please remove your CMakeCache.txt and rerun cmake
```
rm CMakeCache.txt
cmake ..
```

**Comment by caktux** [comment] 2015-04-03 02:09
the other errors are caused by missing ncurses

**Comment by alphaonex86** [comment] 2015-04-03 10:26
*  sys-libs/ncurses
      Latest version available: 5.9-r3
      Latest version installed: 5.9-r3
      Size of files: 2761 KiB                                                                                                                                                                                                                                                  
      Homepage:      http://www.gnu.org/software/ncurses/ http://dickey.his.com/ncurses/                                                                                                                                                                                       
      Description:   console display library                                                                                                                                                                                                                                   
      License:       MIT

**Comment by caktux** [comment] 2015-04-03 18:24
Does that include the development files? You probably need a `-dev` or `-src` package.

**Comment by alphaonex86** [comment] 2015-04-03 18:38
Yes, include, .so is here and I can link over it.

**Comment by caktux** [comment] 2015-04-04 17:24
Must be a cmake or linking problem, I haven't installed Gentoo in over ten years and I won't be able to test this for a while, please report back if you find a solution.

**Closed** 2015-07-28 13:31 UTC
Labels: unconfirmed
