### ISSUE TITLE
Latest develop GPU mining doesn't work on windows/mac.

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#1942] opened 2015-05-16 22:00 UTC
Maybe this happens only in RELEASE mode? (DEBUG and such is set to false)

In logs below, miner is trying to mine while creating the DAG.

[94m  ℹ  [35m23:54:43[0m[30m|[34mmain[0m  Getting work package...
[94m  ℹ  [35m23:54:43[0m[30m|[34mmain[0m  Got work package:
[94m  ℹ  [35m23:54:43[0m[30m|[34mmain[0m    Header-hash: feb1faf15cdbe8732a8f67731d1fca722e72e7d0d43e3ebfcbdbdacaeb4fe839[0m
[94m  ℹ  [35m23:54:43[0m[30m|[34mmain[0m    Seedhash: d705bfceb18862841d146b65702167152de74c08a4c1821a1698fcc414d8978e[0m
[94m  ℹ  [35m23:54:43[0m[30m|[34mmain[0m    Target: 0000000150f07a04d7111e86aaf91a7d50dae1e6df9ea554337af06bbf56c7cb[0m
[97m  ◇  [35m23:54:43[0m[30m|[34mmain[0m  pause took [94m2.7e-05[0m
[97m  ◇  [35m23:54:43[0m[30m|[34mmain[0m  kickOff took [94m0.000122[0m
[94m  ℹ  [35m23:54:43[0m[30m|[34mgpuminer0[0m  workLoop 0 [96m#00000000…[0m [96m#d705bfce…[0m
[94m  ℹ  [35m23:54:44[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 0.5 s
[94m  ℹ  [35m23:54:44[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:44[0m[30m|[34m<unknown>[0m  Loading full DAG of seedhash: [96m#d705bfce…[0m
[94m  ℹ  [35m23:54:44[0m[30m|[34m<unknown>[0m  Loading from libethash...
[32mDAG  [35m23:54:44[0m[30m|[34m<unknown>[0m  Generating DAG file. Progress: 0[0m %
[94m  ℹ  [35m23:54:44[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 1.006 s
[94m  ℹ  [35m23:54:44[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:45[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 1.518 s
[94m  ℹ  [35m23:54:45[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:45[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 2.028 s
[94m  ℹ  [35m23:54:46[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:46[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 2.561 s
[94m  ℹ  [35m23:54:46[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:46[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 3.071 s
[94m  ℹ  [35m23:54:47[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:47[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 3.592 s
[94m  ℹ  [35m23:54:47[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:47[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 4.104 s
[94m  ℹ  [35m23:54:48[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:48[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 4.615 s
[94m  ℹ  [35m23:54:48[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:48[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 5.127 s
[94m  ℹ  [35m23:54:49[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:49[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 5.639 s
[94m  ℹ  [35m23:54:49[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:49[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 6.174 s
[94m  ℹ  [35m23:54:50[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:50[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 6.681 s
[94m  ℹ  [35m23:54:50[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[32mDAG  [35m23:54:50[0m[30m|[34m<unknown>[0m  Generating DAG file. Progress: 1[0m %
[94m  ℹ  [35m23:54:50[0m[30m|[34mmain[0m  Mining on PoWhash [96m#feb1faf1…[0m : 0 H/s = 0 hashes / 7.192 s
[94m  ℹ  [35m23:54:50[0m[30m|[34mmain[0m  Got work package:
[94m  ℹ  [35m23:54:50[0m[30m|[34mmain[0m    Header-hash: 2c54264e2e3cd29b09c641192ea264f8ff9c77922169e3bd35bdab6ccd8ec038[0m
[94m  ℹ  [35m23:54:50[0m[30m|[34mmain[0m    Seedhash: d705bfceb18862841d146b65702167152de74c08a4c1821a1698fcc414d8978e[0m
[94m  ℹ  [35m23:54:50[0m[30m|[34mmain[0m    Target: 00000001511a9d57b437f1b254990183035223ceaf10c26e4291f9a8a5c448a7[0m
[94m  ℹ  [35m23:54:51[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:51[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:52[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:52[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:53[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:53[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[94m  ℹ  [35m23:54:54[0m[30m|[34mgpuminer0[0m  Awaiting DAG
[91m ⚡   [35m23:54:54[0m[30m|[34mmain[0m  Stop worker [94m0.461877[0m s
[97m  ◇  [35m23:54:54[0m[30m|[34mmain[0m  pause took [94m3.86103[0m
[94m  ℹ  [35m23:54:54[0m[30m|[34mgpuminer0[0m  workLoop 1 [96m#d705bfce…[0m [96m#d705bfce…[0m
[97m  ◇  [35m23:54:54[0m[30m|[34mmain[0m  kickOff took [94m0.019226[0m
[101m[1;30m  ✘  [35m23:54:54[0m[30m|[34mgpuminer0[0m  Error GPU mining. GPU memory fragmentation?
[94m  ℹ  [35m23:54:55[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 0.504 s
[94m  ℹ  [35m23:54:55[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 1.017 s
[94m  ℹ  [35m23:54:56[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 1.528 s
[94m  ℹ  [35m23:54:56[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 2.05 s
[32mDAG  [35m23:54:56[0m[30m|[34m<unknown>[0m  Generating DAG file. Progress: 2[0m %
[94m  ℹ  [35m23:54:57[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 2.557 s
[94m  ℹ  [35m23:54:57[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 3.083 s
[94m  ℹ  [35m23:54:58[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 3.594 s
[94m  ℹ  [35m23:54:58[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 4.104 s
[94m  ℹ  [35m23:54:59[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 4.611 s
[94m  ℹ  [35m23:54:59[0m[30m|[34mmain[0m  Mining on PoWhash [96m#2c54264e…[0m : 0 H/s = 0 hashes / 5.123 s
[94m  ℹ  [35m23:54:59[0m[30m|[34mmain[0m  Got work package:
[94m  ℹ  [35m23:54:59[0m[30m|[34mmain[0m    Header-hash: 30a5bd2e121c24593971d567a58f41995a0ceb633e9092aa1df8b82d217f13ba[0m
[94m  ℹ  [35m23:54:59[0m[30m|[34mmain[0m    Seedhash: d705bfceb18862841d146b65702167152de74c08a4c1821a1698fcc414d8978e[0m
[94m  ℹ  [35m23:54:59[0m[30m|[34mmain[0m    Target: 000000015144c5efaae3133f1ce5a31288dd2e77c4dee1f7849cee48030cac02[0m
[32mDAG  [35m23:55:02[0m[30m|[34m<unknown>[0m  Generating DAG file. Progress: 3[0m %
[97m  ◇  [35m23:55:03[0m[30m|[34mmain[0m  pause took [94m3.38119[0m
[91m ⚡   [35m23:55:03[0m[30m|[34mgpuminer0[0m  Worker stopping [94m8.55458[0m s
[94m  ℹ  [35m23:55:03[0m[30m|[34mgpuminer0[0m  workLoop 1 [96m#d705bfce…[0m [96m#d705bfce…[0m
[97m  ◇  [35m23:55:03[0m[30m|[34mmain[0m  kickOff took [94m0.018412[0m
[101m[1;30m  ✘  [35m23:55:03[0m[30m|[34mgpuminer0[0m  Error GPU mining. GPU memory fragmentation?
[94m  ℹ  [35m23:55:03[0m[30m|[34mmain[0m  Mining on PoWhash [96m#30a5bd2e…[0m : 0 H/s = 0 hashes / 0.5 s
[94m  ℹ  [35m23:55:03[0m[30m|[34mmain[0m  Got work package:
[94m  ℹ  [35m23:55:03[0m[30m|[34mmain[0m    Header-hash: 9000e3d83874dbef694a33f8acfe4a2b4a3c73cf3475b67a32a4d9d89700f0e6[0m
[94m  ℹ  [35m23:55:03[0m[30m|[34mmain[0m    Seedhash: d705bfceb18862841d146b65702167152de74c08a4c1821a1698fcc414d8978e[0m
[94m  ℹ  [35m23:55:03[0m[30m|[34mmain[0m    Target: 000000015144c5efaae3133f1ce5a31288dd2e77c4dee1f7849cee48030cac02[0m
[97m  ◇  [35m23:55:07[0m[30m|[34mmain[0m  pause took [94m3.3727[0m
[91m ⚡   [35m23:55:07[0m[30m|[34mgpuminer0[0m  Worker stopping [94m3.9164[0m s
[94m  ℹ  [35m23:55:07[0m[30m|[34mgpuminer0[0m  workLoop 1 [96m#d705bfce…[0m [96m#d705bfce…[0m
[97m  ◇  [35m23:55:07[0m[30m|[34mmain[0m  kickOff took [94m0.025327[0m
[101m[1;30m  ✘  [35m23:55:07[0m[30m|[34mgpuminer0[0m  Error GPU mining. GPU memory fragmentation?
[94m  ℹ  [35m23:55:07[0m[30m|[34mmain[0m  Mining on PoWhash [96m#9000e3d8…[0m : 0 H/s = 0 hashes / 0.502 s
[94m  ℹ  [35m23:55:07[0m[30m|[34mmain[0m  Got work package:
[94m  ℹ  [35m23:55:07[0m[30m|[34mmain[0m    Header-hash: f643d9957f10e10c70565115d7879c31e14a19093a386f868669272485b092a3[0m
[94m  ℹ  [35m23:55:07[0m[30m|[34mmain[0m    Seedhash: d705bfceb18862841d146b65702167152de74c08a4c1821a1698fcc414d8978e[0m
[94m  ℹ  [35m23:55:07[0m[30m|[34mmain[0m    Target: 00000001511aa29cc092ea5cc808ed85e6ada5601387d33fb84f1e19845c3ed3[0m
[32mDAG  [35m23:55:08[0m[30m|[34m<unknown>[0m  Generating DAG file. Progress: 4[0m %
[97m  ◇  [35m23:55:10[0m[30m|[34mmain[0m  pause took [94m3.31611[0m
[91m ⚡   [35m23:55:10[0m[30m|[34mgpuminer0[0m  Worker stopping [94m3.85319[0m s
[97m  ◇  [35m23:55:10[0m[30m|[34mmain[0m  kickOff took [94m0.022704[0m
[94m  ℹ  [35m23:55:10[0m[30m|[34mgpuminer0[0m  workLoop 1 [96m#d705bfce…[0m [96m#d705bfce…[0m
[101m[1;30m  ✘  [35m23:55:10[0m[30m|[34mgpuminer0[0m  Error GPU mining. GPU memory fragmentation?
[94m  ℹ  [35m23:55:11[0m[30m|[34mmain[0m  Mining on PoWhash [96m#f643d995…[0m : 0 H/s = 0 hashes / 0.501 s
[94m  ℹ  [35m23:55:11[0m[30m|[34mmain[0m  Mining on PoWhash [96m#f643d995…[0m : 0 H/s = 0 hashes / 1.008 s
[94m  ℹ  [35m23:55:12[0m[30m|[34mmain[0m  Mining on PoWhash [96m#f643d995…[0m : 0 H/s = 0 hashes / 1.516 s
[94m  ℹ  [35m23:55:12[0m[30m|[34mmain[0m  Mining on PoWhash [96m#f643d995…[0m : 0 H/s = 0 hashes / 2.024 s

**Comment by subtly** [comment] 2015-05-16 23:44
ping @LefterisJP

**Comment by LefterisJP** [comment] 2015-05-17 00:39
Latest develop CPU/GPU mining does not work anywhere actually.

Not after this commit:
https://github.com/ethereum/cpp-ethereum/commit/93752ed1cf83feef36f035661efa10153d20b99e

It's a synchronization issue introduced by that commit. After going in with gdb it seems that `EthashAux::computeFull()` is called by `full()` and has a c++11 lambda to generate the DAG in another thread as seen here (https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/EthashAux.cpp#L194):

```c++
		get()->m_fullGenerator = unique_ptr<thread>(new thread([=](){
			cnote << "Loading full DAG of seedhash: " << _seedHash;
			get()->full(_seedHash, true, [](unsigned p){ get()->m_fullProgress = p; return 0; });
			cnote << "Full DAG loaded";
			get()->m_fullProgress = 0;
			get()->m_generatingFullNumber = NotGenerating;
		}));
```

The problem is that his lambda executes in a different thread and the current thread happilly continues out of the function only to reach this point two stack frames upwards (https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/Ethash.cpp#L137):

```c++
	auto dag = EthashAux::full(w.seedHash);
	h256 boundary = w.boundary;
	unsigned hashCount = 1;
	for (; !shouldStop(); tryNonce++, hashCount++)
	{
		ethashReturn = ethash_full_compute(dag->full, *(ethash_h256_t*)w.headerHash.data(), tryNonce);
		h256 value = h256((uint8_t*)&ethashReturn.result, h256::ConstructFromPointer);
		if (value <= boundary && submitProof(Solution{(Nonce)(u64)tryNonce, h256((uint8_t*)&ethashReturn.mix_hash, h256::ConstructFromPointer)}))
			break;
		if (!(hashCount % 1000))
			accumulateHashes(1000);
	}
}
```

where it exits the `full()` computation thinking it has a dag and then when dereferencing `dag->full` a segfault occurs.

ping @gavofyork

**Comment by gavofyork** [comment] 2015-05-17 11:01
Fixed in latest. Please reopen if still broken after 93752ed

**Closed by gavofyork** 2015-05-17 11:01 UTC
Labels: ethash
