### ISSUE TITLE
build on ubuntu 14.04 following  wiki instruction failed!

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/cpp-ethereum#2901] opened 2015-08-22 15:26 UTC
When I following the wiki's ubuntu installation instruction 
https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu

it build failed at missing library LLVMipa.

[ 29%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o
Linking CXX shared library libevmjit.so
/usr/bin/ld.gold: error: cannot find -lLLVMipa
collect2: error: ld returned 1 exit status
make[2]: *** [evmjit/libevmjit/libevmjit.so.0.9.0.1] Error 1
make[1]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2

anybody know how to fix this?

thanks ahead.

**Comment by ryepdx** [comment] 2015-08-22 19:48
Try again. Looks like a duplicate of #2876, which was resolved with 28b6d0f84f41bc9ea394a3cc1da257697ed73fe6.

**Comment by ryepdx** [comment] 2015-08-22 20:01
Also, if you end up having trouble with CMake complaining about unknown commands after the update, as I just did, try deleting your CMakeCache.txt and CMakeFiles directories.

**Comment by CJentzsch** [comment] 2015-08-22 20:33
fixed by https://github.com/ethereum/cpp-ethereum/pull/2879 and https://github.com/ethereum/cpp-ethereum/pull/2878

**Closed by CJentzsch** 2015-08-22 20:33 UTC
