### ISSUE TITLE
Linux build, what to do?

### ISSUE THREAD

**Issue by Feedz** [ethereum/cpp-ethereum#4127] opened 2017-06-08 15:56 UTC
GCC version 7.1.1
mkdir build
cd build
cmake ..
cmake --build .

http://i.imgur.com/UKTkKSY.png

[ 28%] Building C object libethash/CMakeFiles/ethash.dir/internal.c.o
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c: In function ‘ethash_full_new_internal’:
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c:472:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if (ethash_io_prepare(dirname, seed_hash, &f, (size_t)full_size, true) != ETHASH_IO_MEMO_MISMATCH) {
      ^
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c:477:2: note: here
  case ETHASH_IO_MEMO_MISMATCH:
  ^~~~
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c: In function ‘ethash_light_compute_internal’:
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c:252:24: error: ‘tmp_node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      mix[n].words[w] = fnv_hash(mix[n].words[w], dag_node->words[w]);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c:252:24: error: ‘*((void *)&tmp_node+16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c:252:24: error: ‘*((void *)&tmp_node+32)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/home/ivan/Projects/ethereum/cpp-ethereum/libethash/internal.c:252:24: error: ‘*((void *)&tmp_node+48)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
make[2]: *** [libethash/CMakeFiles/ethash.dir/build.make:87: libethash/CMakeFiles/ethash.dir/internal.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:495: libethash/CMakeFiles/ethash.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by chfast** [comment] 2017-06-08 21:02
Duplicate of #4115.

**Closed by chfast** 2017-06-08 21:02 UTC
