### ISSUE TITLE
OS X Mavericks - Unit-test failure - fatal error: in "BlockSuite/bStates": memory access violation

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3058] opened 2016-08-20 00:34 UTC
See https://travis-ci.org/ethereum/cpp-ethereum/jobs/153709346

```
Mining timeout! Trying again...unknown location:0: fatal error: in "BlockSuite/bStates": memory access violation at address: 0x154516384: non-existent physical address
```

**Comment by chfast** [comment] 2017-02-28 12:26
Duplicate of #3586

**Closed by chfast** 2017-02-28 12:26 UTC
Labels: broken-unit-tests, bug
