### ISSUE TITLE
AlethZero crashes importing blocks on Mac OS

### ISSUE THREAD

**Issue by Benoit9** [ethereum/cpp-ethereum#2141] opened 2015-06-10 09:56 UTC
This is version is AlethZero/v0.9.24/Release/Darwin/clang/int
4e17c58938ae116cb642750401ee330623f236d3
CLEAN

It is a new install, downloading the chain from scratch.

The last imported block is 374395.

App downloads new blocks then crashes, never goes above 374395.

Here is the report: https://gist.github.com/Benoit9/6ebbe5054be7161373f2

**Comment by Benoit9** [comment] 2015-06-10 16:26
It seems to crash in a malloc. I launched again with all other apps closed, it still crashes. This is a 16GB machine.

**Comment by arkpar** [comment] 2015-06-10 16:39
Ran out of stack

**Comment by Benoit9** [comment] 2015-06-10 19:23
Related to this then: https://github.com/ethereum/cpp-ethereum/issues/2139 ?

**Comment by Benoit9** [comment] 2015-06-11 07:02
Looks similar: https://gist.github.com/Benoit9/3c22a09464f2db64c1a0
Is it a recursive call?

If it just a stack size limit, can I do anything to make it run?

**Comment by chfast** [comment] 2015-06-11 08:53
It is a duplicate of #1995. But you might be right that correct stack limit for OSX must be set.

**Comment by Benoit9** [comment] 2015-06-11 09:21
Thanks! Is there a way to clear the hurdle and to run AlethZero at all?

**Comment by chfast** [comment] 2015-06-11 09:24
I'm trying to set the correct stack limit on OSX, but it need to go through buildbot as I don't use OSX.

**Comment by Benoit9** [comment] 2015-06-11 09:48
I am not set up to build from source on OSX, but let me know if I can help with testing.

**Comment by Benoit9** [comment] 2015-06-11 19:35
I tried the buildbot AlethZero-OSX-20150611181529-0.9.25-61-3f94350.dmg version. No luck. Same crash.

**Comment by chfast** [comment] 2015-06-13 11:42
There is a new version of AlethZero available: AlethZero-OSX-20150613082031-0.9.25-61-41397c3.dmg
Can you test it and tell me if it works for you?

**Comment by Benoit9** [comment] 2015-06-13 19:00
Yes, working now. Thank you!

**Comment by chfast** [comment] 2015-06-15 11:32
Fixed by #2167.

**Closed by chfast** 2015-06-15 11:32 UTC
Labels: bug
