### ISSUE TITLE
eth -f does not work on 0.9.0

### ISSUE THREAD

**Issue by alfetopito** [ethereum/cpp-ethereum#1301] opened 2015-03-12 18:53 UTC
When I try to run `eth` with the `-f` option, this is what I get:

```sh
$ eth -f
Ethereum (++) 0.9.0
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
  Based on a design by Vitalik Buterin.

*N* [ 18:43:19 | main ] IP Address: 10.0.2.15  = [LOCAL]
*N* [ 18:43:19 | main ] Id: c1420c8e1cca361c5fd4c0d35ff41b980848db1e41c32e694b2fc65dc32f2fbc88919d42c0faeafbea2dd56f9f7274cdd823fbd0f64a083f189ab99fd1396c1f
*** [ 18:43:19 | main ] Opened blockchain DB. Latest: fa9046e337bbae1b7c0c01eafb61f1ba14bceba8dd4e83bd8a0c3766c1536ffd
*** [ 18:43:19 | main ] Opened state DB.
*** [ 18:43:19 | main ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
Address: 
9138cf8cf1d7c7e7b521d274b7eb0336a5f1c240
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Installed it using the recommend method via the wiki:

```sh
DEBIAN_FRONTEND=noninteractive sudo add-apt-repository ppa:ethereum/ethereum
DEBIAN_FRONTEND=noninteractive sudo add-apt-repository ppa:ethereum/ethereum-dev
DEBIAN_FRONTEND=noninteractive sudo add-apt-repository ppa:ethereum/ethereum-qt
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y eth
```

I guess I could just not use `ethereum-dev` and go for 0.8.2 instead, but I'm also using ethereum's [Dockerfile](https://github.com/ethereum/cpp-ethereum/blob/develop/docker/Dockerfile) which also has the same issue.

**Comment by subtly** [comment] 2015-03-20 22:20
Does this still crash after updating to latest develop?

**Comment by gavofyork** [comment] 2015-03-21 19:14
probably a UPnP issue. if you run with `eth -n off -f` does it work? also if you try on the latest develop branch is it any better?

**Comment by alfetopito** [comment] 2015-03-23 13:09
Hey guys, thanks for the reply.

I still couldn't try it out with the latest dev.
Since when I faced it I did decide to go with 0.8.2 instead and [created a docker file](https://github.com/alfetopito/ethereum-stable) for the stable version.

I'll try again later today or tomorrow using the dev branch.

**Comment by alfetopito** [comment] 2015-03-24 14:14
Using the latest docker file from https://registry.hub.docker.com/u/ethereum/client-cpp/

```bash
# docker run ethereum/client-cpp -f
Ethereum (++) 0.9.1
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
  Based on a design by Vitalik Buterin.

*N* [ 14:11:41 | main ] IP Address: 172.17.0.17  = [LOCAL]
*N* [ 14:11:41 | main ] Id: 7f9999af9fb5ed2a964735705c99e1224a74679629cfeae327e745f6e186085e9431d71409d780e0890ed46142b09957bd7a2aab85b7c8601ba6ff7ac5b8addc
*** [ 14:11:41 | main ] Opened blockchain DB. Latest: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
*** [ 14:11:41 | main ] Opened state DB.
--- [ 14:11:41 | main ] startWorking for thread eth
--- [ 14:11:41 | main ] Spawning eth
Transaction Signer: 5aac56d9bfd444816d8ce9590b434a469c724470
Mining Benefactor: 5aac56d9bfd444816d8ce9590b434a469c724470
--- [ 14:11:41 | main ] startWorking for thread p2p
--- [ 14:11:41 | main ] Spawning p2p
--- [ 14:11:41 | main ] startWorking for thread eth
--- [ 14:11:41 | main ] startWorking for thread miner-0
--- [ 14:11:41 | main ] Spawning miner-0
--- [ 14:11:41 | p2p ] startWorking for thread ethsync
--- [ 14:11:41 | p2p ] Spawning ethsync
--- [ 14:11:41 | p2p ] startWorking for thread anon
--- [ 14:11:41 | p2p ] Spawning anon
*** [ 14:11:41 | eth ] New block on chain: Restarting mining operation.
*** [ 14:11:41 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** [ 14:11:41 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
```

Using `-n off -f` the output is exactly the same.

**Comment by gavofyork** [comment] 2015-03-31 11:41
almost certainly a duplicate of #709

**Comment by gavofyork** [comment] 2015-03-31 11:53
note the first three lines of the (https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu)[wiki]:

```
sudo apt-get -y update
sudo apt-get -y install language-pack-en-base
sudo dpkg-reconfigure locales
```

**Comment by gavofyork** [comment] 2015-03-31 16:58
Closing as duplicate. Reopen if this doesn't fix.

**Closed by gavofyork** 2015-03-31 16:58 UTC
Labels: duplicate
