### ISSUE TITLE
eth_sendTransaction returns empty result

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1999] opened 2015-05-21 09:36 UTC
develop ce205f3

Run eth cli with rpc and send this tx:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from": "0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826", "gas": "0xdbba0", "value": "0x0", "to": "0x9dbe0ff25853853bb7ee85e07fcee4172c5a2151", "data": "0x13f955e1000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000190020000003904195c8b149dba2ef3369368c4ce5cfa389a15bc79f307000000000000000015a1c9c15e580d812ae4e11e7c721107012533ce85916041eafdb4dfa495f97990705d55f5861618e479e28303000000007cdc3cbe07837b94f3c419c9fbf9508ee63c0bbf92910e000000000000000016bccc16446cc881e84c76c7fb162b04794c8805c2ba7cae6b22a18facdd1701dd705d55f5861618d39caa270300000084e0b50a06b2eec8b75b9e9c56d42ae869f99699fca3dc100000000000000000dac9b2eb15716256eb5deb7da391c391c1a16f8ee8189d1e3c36f8a5afdb71471b745d55f58616180fb1b4ec03000000b31dbfb32fa07a35bd60c10c910cd38a6cca4888721317070000000000000000c37f76ad76dcac226c081826c57a2b447de5ff6198754abf4fa6c7a5d6fbcc3548755d55f5861618a0c9c756030000000a7c8143c3cccc895aaa3b9bd95adeb996899e9ced5ae5060000000000000000f4f7a5203c5e4b98674ee33880e5f8756626497e7ad6e39e5b129d0fa4fd073a57755d55f58616186cf4f75700000000000000000000000000000000", "gasPrice": "0x9184e72a000"}],"id":1}' http://localhost:8549
{"id":1,"jsonrpc":"2.0","result":""}
```

I've tried sending the above several times and always empty result by eth.
[Whereas Geth returns a transaction hash (which can be looked up using eth_getTransactionByHash)]

**Comment by gavofyork** [comment] 2015-05-29 13:29
duplicate of #1959

**Closed by gavofyork** 2015-05-29 13:29 UTC
Labels: bug
