### ISSUE TITLE
RPC changes, bug list

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#1252] opened 2015-03-09 18:38 UTC
I list here all the bugs i cam across while adopting ethereum.js to the new RPC endpoints.
As this are probably minor bugs, i will add one comment for each bug:

**Comment by frozeman** [comment] 2015-03-09 18:38
get `getTransactionCount` returns `0x01` and `getBlockTransactionCount` `0x1`

**Comment by frozeman** [comment] 2015-03-09 18:39
```js
{
id: 8,
jsonrpc: "2.0",
method: "eth_getBlockByNumber",
params: ["0x3"]
}
```

returns me an `INVALID_PARAMS` error

**Comment by frozeman** [comment] 2015-03-09 18:41
TODO: add `"pending"` as an default block parameter, when we also want to retrieve pending transactions (before it was `0`)

So we have:

- block number
- `latest`
- `pending`

**Comment by frozeman** [comment] 2015-03-09 18:43
Sending transaction using `eth_sendTransaction` as follows: (i tried all kind of gas values)

```js
{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0xfd9801e0aa27e54970936aa910a7186fdf5549bc",
"to":"0xd46e8dd67c5d32be8058bb8eb970870f072445675",
"gas":"0x1bc16d674ec80000",
"gasPrice":"0x6c6b935b8bbd400000",
"value":"0x56bc75e2d63100000"}],
"id":5}
```
Gives me the following error:

```js
*** [ 19:23:03 | main ] New transaction {46e8dd67…/7$100000000000000000000+2000000000000000000@2000000000000000000000<-fd9801e0… #0}
!!! [ 19:23:03 | eth ] Sync went wrong
 /Users/frozeman/Developer/cpp-ethereum/libethereum/Executive.cpp(87): Throw in function bool dev::eth::Executive::setup()
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::NotEnoughCash>
std::exception::what: std::exception
```

**Comment by frozeman** [comment] 2015-03-09 18:44
`eth_call` with:

```js
{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xd46e8dd67c5d32be8058bb8eb970870f072445675",
"data":"0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"},"latest"],"id":6}
```

gives me an `INVALID_PARAMS` error

**Comment by frozeman** [comment] 2015-03-09 19:13
For `eth_newBlockFilter` we should change the options to `pending` and `latest` to match the defaultBlock (its also more clear than `chain`)

**Comment by debris** [comment] 2015-03-10 07:32
> get `getTransactionCount` returns `0x01` and `getBlockTransactionCount` `0x1`

- both are correct, not an issue

> ```js
> {
> id: 8,
> jsonrpc: "2.0",
> method: "eth_getBlockByNumber",
> params: ["0x3"]
> }
> ```
> returns me an `INVALID_PARAMS` error

also works fine, you passed only one of two required params [#wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber)

> TODO: add "pending" as an default block parameter, when we also want to retrieve pending transactions (before it was 0)

fixed in d0b75e59d0a467230edfa923d0744f28a9e8b8ef

 
> Sending transaction using `eth_sendTransaction` as follows: (i tried all kind of gas values)
> ```js
> {"jsonrpc":"2.0","method":"eth_sendTransaction","params": [{"from":"0xfd9801e0aa27e54970936aa910a7186fdf5549bc",
"to":"0xd46e8dd67c5d32be8058bb8eb970870f072445675",
"gas":"0x1bc16d674ec80000",
"gasPrice":"0x6c6b935b8bbd400000",
"value":"0x56bc75e2d63100000"}],
"id":5}
> ```
> Gives me the following error:
> ```js
> *** [ 19:23:03 | main ] New transaction {46e8dd67…/7$100000000000000000000+2000000000000000000@2000000000000000000000<-fd9801e0… #0}
> !!! [ 19:23:03 | eth ] Sync went wrong
> /Users/frozeman/Developer/cpp-ethereum/libethereum/Executive.cpp(87): Throw in function bool dev::eth::Executive::setup()
> Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::NotEnoughCash>
std::exception::what: std::exception
> ```

- Couldn't reproduce. Can we have a separate issue for this?

>`eth_call` with:
> ```js
{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xd46e8dd67c5d32be8058bb8eb970870f072445675",
"data":"0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"},"latest"],"id":6}
```
> gives me an `INVALID_PARAMS` error
(ps i didn't check of the data field is a proper data value..)

- According to [wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call) this request is not correct. `eth_call` accepts only 1 param. Should I make this two?

> For `eth_newBlockFilter` we should change the options to `pending` and `latest` to match the defaultBlock (its also more clear than `chain`)

- Good idea, I've changed this in 5eff1f65d34a23dcb0e9e4a250b756723075fd9f. Now It accepts `pending` and `chain`/`latest`.

**Comment by frozeman** [comment] 2015-03-10 09:41
The to is empty in an transaction inside a block:
```js
{...
sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
"size: 0stateRoot: "0x0af203810f27335b87d04f92d00091d2000b7ed12a3bcc36728899a26d0a7ca1
"timestamp: 1425979526
totalDifficulty: BigNumber
transactions: [{
   from: "0xfd9801e0aa27e54970936aa910a7186fdf5549bc"
   gas: 21000gasPrice: BigNumber
   hash: "0xbd2a4d674db08d42ea26057bd0256715334d510f9cafd31386c376282b35c176"
   input: "0x0000000000000000000000000000000000000000000000000000000000000000"
   nonce: "0x07"
   to: "0x0000000000000000000000000000000000000000",
  ...
}
}]
```

**Comment by frozeman** [comment] 2015-03-10 09:42
If i set the second parameter to `false` in `eth_getBlock()`, it returns no transaction object. I expect an array with transaction hashes.

**Comment by debris** [comment] 2015-03-10 09:53
> If i set the second parameter to `false` in `eth_getBlock()`, it returns no transaction object. I expect an array with transaction hashes.

- the error occured in `eth_getTransactionByNumber`. fixed in 9abeaf28593545646a6923590a08295e7db7db3e

**Comment by frozeman** [comment] 2015-03-10 11:39
More bugs

- [ ] the "to" is still empty in transactions
- [ ] and "uncles" are not there because there are none?
- [ ] "children" as well? (was in the js docs, but not in the RCP specs), should we add it?
- [ ] the block hash has no 0x in front

**Comment by frozeman** [comment] 2015-03-10 11:43
`eth_getTransactionByBlockHashAndIndex` and the same for `eth_getTransactionByBlockHashAndIndex`, it doesnt matter waht index i give, it returns me a transaction.

**Comment by debris** [comment] 2015-03-10 12:06
> `eth_getTransactionByBlockHashAndIndex` and the same for `eth_getTransactionByBlockHashAndIndex`, it doesnt matter waht index i give, it returns me a transaction.

> Seems like this is an empty transaction, but with a hash

> ```js
from: "0x0000000000000000000000000000000000000000",
gas: 0
gasPrice: BigNumber
hash: "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
input: "0x0000000000000000000000000000000000000000000000000000000000000000"
nonce: "0x00"
to: "0x0000000000000000000000000000000000000000"
value: BigNumber
```

- Input params for `eth_getTransactionByBlockHashAndIndex` are incorrect, and returned transaction does not exist. Returned hash is sha3 of zeros. We may return an error here in future, but that's and improvement. Current result is ok

- Please also paste valid json object in examples, not js.

**Comment by gavofyork** [comment] 2015-03-21 19:39
separate issues for each issue, please.

**Comment by gavofyork** [comment] 2015-03-21 19:41
reopen remaining issues individually.

**Closed** 2015-03-21 19:41 UTC
Labels: invalid
