### ISSUE TITLE
Windows latest build crashes when activating Force Mining and Mine at the same time

### ISSUE THREAD

**Issue by Georgi87** [ethereum/cpp-ethereum#1427] opened 2015-03-26 12:58 UTC
No matter if a private blockchain is used, in any case the AlethZero browser crashes if I try to enfore mining. I am using the latest commit.

Is there any version that does not crash and supports the new ABI format?

**Comment by joeykrug** [comment] 2015-03-27 23:22
I get this same issue (actually works on OS X, but not windows / ubuntu)

**Comment by gavofyork** [comment] 2015-03-28 08:19
any chance you could run a debug build under GDB and provide a backtrace?

**Comment by alexfisher** [comment] 2015-03-28 13:57
I had this issue on Ubuntu, too.  First time using the debug build and GDB, but tried to produce a backtrace for you, Gavin:

[New Thread 0x7fff5a7fc700 (LWP 17306)]
	*** [ 09:52:33 AM | miner-0 ] Pre-reward stateRoot: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
	*** [ 09:52:33 AM | miner-1 ] Pre-reward stateRoot: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
	*** [ 09:52:33 AM | miner-2 ] Pre-reward stateRoot: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
	*** [ 09:52:33 AM | miner-3 ] Pre-reward stateRoot: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e

	Program received signal SIGSEGV, Segmentation fault.
	[Switching to Thread 0x7fff5a7fc700 (LWP 17306)]
	0x00007ffff648579d in ethash_full () from /home/alex/cpp-ethereum/build/libethcore/libethcore.so
	(gdb) backtrace
	#0  0x00007ffff648579d in ethash_full () from /home/alex/cpp-ethereum/build/libethcore/libethcore.so
	#1  0x00007ffff64322ee in ethash_compute_full (ret=0x7fff5a7fb600, full=0x7fff0ddf8010, params=0x7fff5a7fb660, 
		header_hash=0x7fff5a7fb640 "\177חfwg\006f'b\234\203\331ə\245ߝ\227\203\232=\242\364ZҁƳ'߰\200\370\377?", 
		nonce=14614558143851509203) at /home/alex/cpp-ethereum/libethcore/../libethash/ethash.h:93
	#2  0x00007ffff6433f2a in dev::eth::Ethasher::Miner::mine (this=0x7fff5a7fb600, _nonce=14614558143851509203)
		at /home/alex/cpp-ethereum/libethcore/Ethasher.h:89
	#3  0x00007ffff643262e in dev::eth::EthashCPU::mine (this=0xf95e9c, _header=..., _msTimeout=100, _continue=true, _turbo=false)
		at /home/alex/cpp-ethereum/libethcore/ProofOfWork.cpp:103
	#4  0x00007ffff68a9156 in dev::eth::State::mine (this=0xf95540, _msTimeout=100, _turbo=false)
		at /home/alex/cpp-ethereum/libethereum/State.cpp:790
	#5  0x00007ffff67d05ec in dev::eth::LocalMiner::doWork (this=0xf954d0) at /home/alex/cpp-ethereum/libethereum/Miner.cpp:69
	#6  0x00007ffff57c49ef in dev::Worker::__lambda0::operator() (__closure=0x2089e20)
		at /home/alex/cpp-ethereum/libdevcore/Worker.cpp:46
	#7  0x00007ffff57c5ea8 in std::_Bind_simple<dev::Worker::startWorking()::__lambda0()>::_M_invoke<>(std::_Index_tuple<>) (
		this=0x2089e20) at /usr/include/c++/4.8/functional:1732
	#8  0x00007ffff57c5dff in std::_Bind_simple<dev::Worker::startWorking()::__lambda0()>::operator()(void) (this=0x2089e20)
		at /usr/include/c++/4.8/functional:1720
	#9  0x00007ffff57c5d98 in std::thread::_Impl<std::_Bind_simple<dev::Worker::startWorking()::__lambda0()> >::_M_run(void) (
		this=0x2089e08) at /usr/include/c++/4.8/thread:115
	#10 0x00007ffff1dacbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
	#11 0x00007ffff2982182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
	#12 0x00007ffff151447d in clone () from /lib/x86_64-linux-gnu/libc.so.6
	(gdb)

**Comment by alexfisher** [comment] 2015-03-28 14:14
Discovered there's a more detailed full backtrace.  Pasting below:

    #0  0x00007ffff648579d in ethash_full () from /home/alex/cpp-ethereum/build/libethcore/libethcore.so
    No symbol table info available.
    #1  0x00007ffff64322ee in ethash_compute_full (ret=0x7fff5a7fb600, full=0x7fff0ddf8010, params=0x7fff5a7fb660, 
        header_hash=0x7fff5a7fb640 "\177חfwg\006f'b\234\203\331ə\245ߝ\227\203\232=\242\364ZҁƳ'߰\200\370\377?", 
        nonce=14614558143851509203) at /home/alex/cpp-ethereum/libethcore/../libethash/ethash.h:93
    No locals.
    #2  0x00007ffff6433f2a in dev::eth::Ethasher::Miner::mine (this=0x7fff5a7fb600, _nonce=14614558143851509203)
        at /home/alex/cpp-ethereum/libethcore/Ethasher.h:89
    No locals.
    #3  0x00007ffff643262e in dev::eth::EthashCPU::mine (this=0xf95e9c, _header=..., _msTimeout=100, _continue=true, _turbo=false)
        at /home/alex/cpp-ethereum/libethcore/ProofOfWork.cpp:103
            val = {m_data = {_M_elems = "\360\266\177Z\377\177\000\000\032\236f", '\000' <repeats 20 times>}}
            m = {m_ethashReturn = {
                result = "x\265\177Z\377\177\000\000\000\336\377\361\377\177\000\000P\267\177Z\377\177\000\000\000\270\177Z\377\177\000", 
                mix_hash = "\004\000\000\000\001\000\000\000\001\000\000\000\004\000\000\000\004\000\000\000\001\000\000\000\004\000\000\000\377\177\000"}, m_headerHash = {m_data = {_M_elems = "\177חfwg\006f'b\234\203\331ə\245ߝ\227\203\232=\242\364ZҁƳ'߰"}}, m_params = {
                full_size = 1073739904, cache_size = 16776896}, m_datasetPointer = 0x7fff0ddf8010}
            tid = {_M_thread = 140734711711488}
            tryNonce = 14614558143851509203
            startTime = {__d = {__r = 18756229222243}}
            best = 9.9999999999999997e+98
            __PRETTY_FUNCTION__ = "std::pair<dev::eth::MineInfo, dev::eth::EthashCPU::Proof> dev::eth::EthashCPU::mine(const dev::eth::BlockInfo&, unsigned int, bool, bool)"
            ret = {first = {requirement = 239, best = 9.9999999999999997e+98, hashes = 0, completed = false}, second = {nonce = {
                  m_data = {_M_elems = "\000\000\000\000\000\000\000"}}, mixHash = {m_data = {_M_elems = '\000' <repeats 31 times>}}}}
            s_eng = {static word_size = <optimized out>, static state_size = 312, static shift_size = <optimized out>, 
              static mask_bits = <optimized out>, static xor_mask = <optimized out>, static tempering_u = <optimized out>, 
              static tempering_d = <optimized out>, static tempering_s = <optimized out>, static tempering_b = <optimized out>, 
              static tempering_t = <optimized out>, static tempering_c = <optimized out>, static tempering_l = <optimized out>, 
              static initialization_multiplier = <optimized out>, static default_seed = <optimized out>, _M_x = {16076745341103851443, 
                14326089631498743541, 5199789679287780638, 4055525433489147962, 4463812425800202651, 7495592197486057806, 
                1614845839055629183, 16510934622279405081, 10650927134280882049, 2579329768433081519, 5317102041349763086, 
                3905497402156988413, 9210220363794494325, 9627965852113546761, 6196280065904746682, 16021557454511836478, 
                1566599134914003031, 10635124080653964555, 1833196866417311010, 10503635267003308725, 7122018273906066309, 
                5912616721556406559, 3675158010307299854, 4701381046284583794, 5487862566465787948, 1078543536275818620, 
                6883976008640009902, 9276402509023130759, 6018705306872495919, 17839405167012785136, 5512708525645588695, 
                14051642269697198635, 7895212069985412037, 11591525296191323318, 2747973992811002003, 10080838597048017315, 
                9597262491386100857, 7972200773356295380, 17404010011667248913, 729140719573199974, 6742205911545950417, 
                9485198182510131475, 141109031978504571, 11682518632337056703, 16291533932114119299, 4188111528507918521, 
                9395429311397253684, 8461596218548636034, 14224086774706652816, 7234825795065245774, 11863032825637227104, 
                18249259829213204638, 8199446949022074932, 14608466639662828928, 14166066975189425346, 18429162548867464425, 
                6577496955355166635, 7914709380212140229, 17865770957852795169, 6873728887798959683, 7246080798649985297, 
                3691067373057828608, 17762005013371038055, 12088665458887015952, 15292251823296921681, 16679549333811652598, 
                12309878962957251725, 16004298019834640261, 13834157347120288194, 14356262968055249304, 3482817388124245740, 
                17892245712701189496, 9986670532173623549, 1074622976875988165, 9984916679666104145, 6174335508988135573, 
                206496558891618486, 11978999127412428830, 7956855782202654387, 1096583500160615465, 95910357601520512, 
                12491932119264984165, 1556307269939287864, 14156737593250663881, 13920297986411570231, 6855049035801919868, 
                10494519133827357959, 14676737113770467416, 8396109221183541992, 15552925358801363430, 706849759348178094, 
                12218831104130591784, 2669335488835870817, 6835082010816723056, 3190429144687381528, 564608531963273410, 
                16544863109866837418, 15002890504288460762, 5715733004432659853, 14447194238163952797, 12780297294014912150, 
                16892009993189857342, 17257731028298358499, 5449392415209757498, 9708641215891418924, 13195900879880175558, 
                3742010300337192708, 7616687528394690745, 5860783013381091896, 3402099760541586699, 16801710459429074729, 
                16157345625033426874, 7086036099683915936, 4856384725057173365, 5587570156775832104, 8538530035862228592, 
                1104702245380506738, 6538418056242945273, 17778424368549976542, 793742780386988133, 9880762249825527030, 
                3201999480164767039, 5420736673794314264, 8974129156975064229, 13759969147773429571, 17866477005305613581, 
                7090500447416713309, 3662472253575887592, 14254858851880902815, 16886363292620759032, 10004040444753296971, 
                14130411558602385602, 9696634496178922339, 5863010504097344878, 4771372936742349989, 15002141124596958876, 
                5052727741343521441, 15412391253056382330, 212510682436752504, 7385430226116361209, 5718734168142202905, 
                7872620540297498707, 15451434900017100189, 15328281637028409306, 10287246179728835791, 2307737490283796182, 
                8667119867195920271, 1228603634846748378, 16581457648934058105, 16633769795228807192, 15609979044185849796, 
                16649883676727965666, 10574726504259764002, 11173813580773895337, 6336255917175744204, 2799394395164473288, 
                1783203387366358683, 17697793492778431266, 7758257046176629625, 598561417816178624, 12474851242574889043, 
                6741322990335904755, 13114258424324190431, 2191229607753541560, 3427916307984387707, 5236840537111065027, 
                12745456599668891714, 4743535460650192763, 14605905199174519251, 14889415978709695662, 5668677388306801924, 
                4843405780412410347, 17833310720715352531, 393244923117044998, 8324445571911117038, 12278717731772717500, 
                13663022071795547532, 18437159142212290989, 15578660064786142456, 663127680701985970, 48690568578128730, 
                6755323856958086007, 7607591963870643176, 15033415550415771636, 16072676717649878068, 6748002619328274368, 
                8219767173076856238, 17039843667707762890, 8187418370258153270, 5822563144337258859, 9835349816730419729, 
                52454057549729743, 8904005761218650086, 10507996070995661630, 7516210467477430145, 3919829839942727972, 
                4652719053602325012, 3710412832077094478, 2571744963528595774, 10203324428973052981...}, _M_p = 22}
            boundary = {m_data = {_M_elems = "\000\000\200", '\000' <repeats 28 times>}}
            hashCount = 0
            result = {nonce = {m_data = {_M_elems = "\000\000\000\000\000\000\000"}}, mixHash = {m_data = {
                  _M_elems = '\000' <repeats 31 times>}}}
    #4  0x00007ffff68a9156 in dev::eth::State::mine (this=0xf95540, _msTimeout=100, _turbo=false)
        at /home/alex/cpp-ethereum/libethereum/State.cpp:790
            ret = {requirement = 0, best = 9.9999999999999997e+98, hashes = 0, completed = false}
            r = {nonce = {m_data = {_M_elems = "\000\000\000\000\000\000\000"}}, mixHash = {m_data = {
                  _M_elems = '\000' <repeats 31 times>}}}
    #5  0x00007ffff67d05ec in dev::eth::LocalMiner::doWork (this=0xf954d0) at /home/alex/cpp-ethereum/libethereum/Miner.cpp:69
            mineInfo = {requirement = 0, best = 9.9999999999999997e+98, hashes = 0, completed = false}
    #6  0x00007ffff57c49ef in dev::Worker::__lambda0::operator() (__closure=0x2089e20)
        at /home/alex/cpp-ethereum/libdevcore/Worker.cpp:46
            this = 0xf954e8
    #7  0x00007ffff57c5ea8 in std::_Bind_simple<dev::Worker::startWorking()::__lambda0()>::_M_invoke<>(std::_Index_tuple<>) (
        this=0x2089e20) at /usr/include/c++/4.8/functional:1732
    No locals.
    #8  0x00007ffff57c5dff in std::_Bind_simple<dev::Worker::startWorking()::__lambda0()>::operator()(void) (this=0x2089e20)
        at /usr/include/c++/4.8/functional:1720
    No locals.
    #9  0x00007ffff57c5d98 in std::thread::_Impl<std::_Bind_simple<dev::Worker::startWorking()::__lambda0()> >::_M_run(void) (
        this=0x2089e08) at /usr/include/c++/4.8/thread:115
    No locals.
    #10 0x00007ffff1dacbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    No symbol table info available.
    #11 0x00007ffff2982182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    No symbol table info available.
    #12 0x00007ffff151447d in clone () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.

**Comment by Georgi87** [comment] 2015-03-28 20:37
I finally got it wokring on Ubuntu. The reason was that the dag cache was not created at the time I tried to start mining. Unfortunately creating the dag chache on Windows didn't solve the problem. It still crashes, when I want to enable force mining and click "Mine".

**Comment by mtbitcoin** [comment] 2015-03-30 15:56
Yup, confirmed that it still does not work on windows with the latest build. It will crash.

**Comment by gavofyork** [comment] 2015-03-31 16:58
please check with latest develop - there was a recent fix.

**Comment by mtbitcoin** [comment] 2015-03-31 19:01
just downloaded http://build.ethdev.com/builds/Windows%20C%2B%2B%20develop%20branch/AlethZero-Win32-latest.7z

Still the same, it crashes

**Comment by joeykrug** [comment] 2015-03-31 20:43
Still crashes for me as well

**Comment by joeykrug** [comment] 2015-04-01 02:58
Oh --- might be because windows develop build is failing

**Comment by atomrigs** [comment] 2015-04-02 14:45
The lastest build of
AlethZero-Win32-20150402134506-0.9.1-59-8-5c41250
has the same issue.

**Comment by joeykrug** [comment] 2015-04-02 14:54
Yeah same here, crashes

**Comment by mtbitcoin** [comment] 2015-04-03 04:31
The auto build system for develop is compiling correctly. But it still crashes with the latest develop

**Comment by tinybike** [comment] 2015-04-04 06:13
I'm also experiencing this bug -- AlethZero v0.9.2 binary on Windows 7.  Crashes when I mine + force mine.

**Comment by tinybike** [comment] 2015-04-04 06:24
Here's the output when I run it with GDB:
```
(gdb) target exec alethzero.exe
(gdb) run
Starting program: C:\Users\jack\Downloads\AZ-cuttingedge\alethzero.exe alethzero.exe
[New Thread 3972.0xeb0]
State root: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
Block Hash: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0
x9178D0F23C965D81F0834A4C72C6253CE6830F4022B1359AAEBFC1ECBA442D4E, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00", 0x20000, 0x0, 0x2FEFD8, 0x0, 0x0, 0x0, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", "\x00\x00\x00\x00\x00\x00\x00*" ], [ ], [ ] ]
Block Hex: f901f8f901f3a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a09178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4ea056e81f171bcc55a6ff8345e692c0f86e5b4
8e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000008302000080832fefd8808080a0000000000000000000000000000000000000000000000000000000000000000088000000000000002ac0c0
eth Network protocol version: 60
Client database version: 11784
[New Thread 3972.0x1090]
*N* [ 23:17:33 | main ] Id: a11cf2f8da7bdfc9e0599df18ece8a67b85f38de84aa89862afe325c22a4e630de16aab14e43ff54b0fb8e4450ac5c0d3e416259b01d6bd8932e4d1cc95d9946
warning: *N* [ 23:17:33 | main ] Id: a11cf2f8da7bdfc9e0599df18ece8a67b85f38de84aa89862afe325c22a4e630de16aab14e43ff54b0fb8e4450ac5c0d3e416259b01d6bd8932e4d1cc95d9946
warning:

*** [ 23:17:33 | main ] Opened blockchain DB. Latest: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
warning: *** [ 23:17:33 | main ] Opened blockchain DB. Latest: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
warning:

*** [ 23:17:33 | main ] Opened state DB.
warning: *** [ 23:17:33 | main ] Opened state DB.
warning:

[New Thread 3972.0x128c]
[New Thread 3972.0x5c8]
[New Thread 3972.0x13e4]
[New Thread 3972.0x984]
[New Thread 3972.0x168]
[New Thread 3972.0xcdc]
[New Thread 3972.0x890]
[New Thread 3972.0xef0]
QtWebEngineProcess not found at location C:/Users/jack/Downloads/AZ-cuttingedge/bin\QtWebEngineProcess.exe. Trying fallback path...
[New Thread 3972.0x848]
[New Thread 3972.0x1378]
[New Thread 3972.0xa84]
[New Thread 3972.0x13c0]
[New Thread 3972.0x158]
[Thread 3972.0x13c0 exited with code 0]
[New Thread 3972.0xfa8]
[New Thread 3972.0x1220]
[New Thread 3972.0x1348]
[New Thread 3972.0x12b0]
[New Thread 3972.0x354]
[New Thread 3972.0xa44]
[New Thread 3972.0xcbc]
[New Thread 3972.0x13a0]
[New Thread 3972.0x6c8]
[New Thread 3972.0xcfc]
[New Thread 3972.0xa80]
[New Thread 3972.0x130c]
[New Thread 3972.0x80c]
[New Thread 3972.0xce8]
[New Thread 3972.0x1158]
[New Thread 3972.0x2e0]
[New Thread 3972.0x1328]
[New Thread 3972.0xca4]
[New Thread 3972.0x840]
[New Thread 3972.0x1160]
[New Thread 3972.0xb7c]
[New Thread 3972.0xdfc]
[New Thread 3972.0x1184]
[New Thread 3972.0xaa4]
[New Thread 3972.0x9bc]
[New Thread 3972.0xbe8]
[New Thread 3972.0xee4]
[New Thread 3972.0xd98]
[New Thread 3972.0x10e0]
"about:blank"
*** [ 23:17:37 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
warning: *** [ 23:17:37 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
warning:

QWindowsWindow::setGeometryDp: Unable to set geometry 1690x1871+0+20 on QWidgetWindow/'MainWindow'. Resulting geometry:  1370x753+0+20 (frame: 8, 30, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 634x753, maximum size: 16777215x16777215).
*** [ 23:17:38 | main ] FIRING WATCH 5 1
warning: *** [ 23:17:38 | main ] FIRING WATCH 5 1
warning:

[New Thread 3972.0x1230]
[0403/231740:ERROR:texture_manager.cc(1561)] [.RenderCompositor-007EAED8]GL ERROR :GL_INVALID_ENUM : glTexImage2D: <- error from previous GL command
[New Thread 3972.0x13c0]
[New Thread 3972.0x2e8]
[New Thread 3972.0xfb4]
[New Thread 3972.0xfe8]
[New Thread 3972.0x71c]
[New Thread 3972.0xee0]
[New Thread 3972.0x1270]
[New Thread 3972.0xf54]

Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 3972.0x71c]
0x52a874f1 in Qt5WebEngineCore!?d_func@WebContentsAdapter@@ABEPBVWebContentsAdapterPrivate@@XZ () from C:\Users\jack\Downloads\AZ-cuttingedge\Qt5WebEngineCore.dll
(gdb) bt
#0  0x52a874f1 in Qt5WebEngineCore!?d_func@WebContentsAdapter@@ABEPBVWebContentsAdapterPrivate@@XZ () from C:\Users\jack\Downloads\AZ-cuttingedge\Qt5WebEngineCore.dll
#1  0x6b3ac976 in MSVCP120!?global@locale@std@@SA?AV12@ABV12@@Z () from C:\Windows\system32\msvcp120.dll
#2  0x627fb3be in callnewh () from C:\Windows\system32\msvcr120.dll
#3  0x627ddab8 in fcloseall () from C:\Windows\system32\msvcr120.dll
#4  0x3ffff880 in ?? ()
#5  0x05029b6c in ?? ()
#6  0x6278ee1f in MSVCR120!??2@YAPAXI@Z () from C:\Windows\system32\msvcr120.dll
#7  0x00d88a16 in ?? ()
#8  0x00d88f53 in ?? ()
#9  0x00d89373 in ?? ()
#10 0x00d32970 in ?? ()
#11 0x00d566bb in ?? ()
#12 0x00e300ad in ?? ()
#13 0x00e300ea in ?? ()
#14 0x6b3af33c in MSVCP120!?_Release@_Pad@std@@QAEXXZ () from C:\Windows\system32\msvcp120.dll
#15 0x00000000 in ?? ()
```

**Comment by caktux** [comment] 2015-04-04 06:44
webengine missing in Windows dependencies

**Comment by gavofyork** [comment] 2015-04-06 15:30
please check once more with latest develop - there was quite a lot changed recently.

**Comment by Smithgift** [comment] 2015-04-06 18:47
Checking mine+force mine on the latest develop on my poor ubuntu laptop, it has yet to crash, though it has yet to mine, either. I suspect it is busy with the DAG cache at the moment--this is not the fastest of computers.

**Comment by Smithgift** [comment] 2015-04-06 18:55
I can confirm alethzero will successfully mine on ubuntu, even on a relatively weak computer.

**Comment by mtbitcoin** [comment] 2015-04-06 19:57
@Smithgift The issue here as per the title is with the Windows build. So far no one seems to be able to mine on the latest develop

**Comment by atomrigs** [comment] 2015-04-06 20:28
AlethZero-Win32-20150406151931-0.9.5-60-9-384853a.7z
still crashes when force mining + mining on Windows 7.
both on private and public chains.

**Comment by gavofyork** [comment] 2015-04-07 00:02
Almost certainly a 1GB allocation bug.Will probably be fixed with a memory-mapped file.

**Comment by gavofyork** [comment] 2015-04-07 00:04
Probably another TODO for @LefterisJP

**Comment by gavofyork** [comment] 2015-04-20 08:27
Works for 64-bit build

**Closed by gavofyork** 2015-04-20 08:27 UTC
Labels: bug, core, ethash, priority, showstopper, windows
